import {
  access,
  mkdir,
  readFile,
  readdir,
  rm,
  stat,
  writeFile,
} from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { collectPluginGatewayMetadata } from "../component/plugin.js";
import type { PluginDefinition, PluginGatewayRuntimeMethods } from "../types.js";

const GENERATED_MARKER = "// @generated by convex-zen generate. DO NOT EDIT.";
const RESERVED_CORE_FUNCTION_NAMES = new Set([
  "getSession",
  "signIn",
  "signOut",
  "plugin",
  "core",
]);
const nodeRequire = createRequire(import.meta.url);

export interface GenerateOptions {
  cwd: string;
  check: boolean;
  verbose: boolean;
}

export interface GenerateResult {
  created: string[];
  updated: string[];
  deleted: string[];
  unchanged: string[];
  warnings: string[];
}

type GeneratedFile = {
  absolutePath: string;
  relativePath: string;
  content: string;
};

type PackageDescriptor = {
  dir: string;
  name: string;
  packageJson: Record<string, unknown>;
};

type AuthFunctionKind = "query" | "mutation" | "action";
type CoreFunctionMeta = Record<string, AuthFunctionKind>;
type PluginFunctionMeta = Record<string, Record<string, AuthFunctionKind>>;
type ResolvedAuthSource = {
  absolutePath: string;
  relativePath: string;
};
type LoadedPluginDefinition = {
  definition: PluginDefinition;
  componentImportPath: string;
  gatewaySourcePath: string;
  childName: string;
  gatewayFunctions: PluginGatewayRuntimeMethods;
};

function normalizeContent(content: string): string {
  const trimmed = content.trimEnd();
  return trimmed.endsWith("\n") ? trimmed : `${trimmed}\n`;
}

async function fileExists(filePath: string): Promise<boolean> {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

function splitPackageSpecifier(moduleSpecifier: string): {
  packageName: string;
  subpath: string;
} {
  if (moduleSpecifier.startsWith("@")) {
    const [scope, name, ...rest] = moduleSpecifier.split("/");
    return {
      packageName: [scope, name].filter(Boolean).join("/"),
      subpath: rest.join("/"),
    };
  }
  const [name, ...rest] = moduleSpecifier.split("/");
  return {
    packageName: name ?? moduleSpecifier,
    subpath: rest.join("/"),
  };
}

function readExportTarget(
  exportsField: unknown,
  key: "." | `./${string}`
): string | null {
  if (!exportsField || typeof exportsField !== "object") {
    return null;
  }
  const record = exportsField as Record<string, unknown>;
  const entry = record[key];
  if (!entry) {
    return null;
  }
  if (typeof entry === "string") {
    return entry;
  }
  if (typeof entry === "object" && entry !== null) {
    const importTarget = (entry as Record<string, unknown>).import;
    if (typeof importTarget === "string") {
      return importTarget;
    }
    const defaultTarget = (entry as Record<string, unknown>).default;
    if (typeof defaultTarget === "string") {
      return defaultTarget;
    }
    const typesTarget = (entry as Record<string, unknown>).types;
    if (typeof typesTarget === "string") {
      return typesTarget;
    }
  }
  return null;
}

async function findWorkspacePackage(
  authSource: ResolvedAuthSource,
  packageName: string
): Promise<PackageDescriptor | null> {
  const workspaceRoot =
    (await findWorkspaceRoot(path.dirname(authSource.absolutePath))) ??
    (await findWorkspaceRoot(path.dirname(fileURLToPath(import.meta.url))));
  if (!workspaceRoot) {
    return null;
  }
  const packagesDir = path.join(workspaceRoot, "packages");
  const packageDirs = await readdir(packagesDir).catch(() => []);
  for (const packageDirName of packageDirs) {
    const dir = path.join(packagesDir, packageDirName);
    const packageJsonPath = path.join(dir, "package.json");
    if (!(await fileExists(packageJsonPath))) {
      continue;
    }
    const packageJson = JSON.parse(await readFile(packageJsonPath, "utf8")) as Record<
      string,
      unknown
    >;
    if (packageJson.name !== packageName) {
      continue;
    }
    return {
      dir,
      name: packageName,
      packageJson,
    };
  }
  return null;
}

async function resolvePackageImportFromDescriptor(
  packageDescriptor: PackageDescriptor,
  moduleSpecifier: string
): Promise<string | null> {
  const { packageName, subpath } = splitPackageSpecifier(moduleSpecifier);
  if (packageDescriptor.name !== packageName) {
    return null;
  }
  const exportKey = subpath.length > 0 ? (`./${subpath}` as const) : ".";
  const exportTarget =
    readExportTarget(packageDescriptor.packageJson.exports, exportKey) ??
    (subpath.length === 0 && typeof packageDescriptor.packageJson.main === "string"
      ? packageDescriptor.packageJson.main
      : null);
  if (exportTarget) {
    return pathToFileURL(
      path.resolve(packageDescriptor.dir, exportTarget)
    ).href;
  }

  const fallbackCandidates =
    subpath.length > 0
      ? [
          subpath,
          `${subpath}.js`,
          `${subpath}.mjs`,
          `${subpath}.cjs`,
          `${subpath}.ts`,
          path.join(subpath, "index.js"),
          path.join(subpath, "index.mjs"),
          path.join(subpath, "index.cjs"),
          path.join(subpath, "index.ts"),
        ]
      : ["index.js", "index.mjs", "index.cjs", "index.ts"];

  for (const candidate of fallbackCandidates) {
    const candidatePath = path.resolve(packageDescriptor.dir, candidate);
    if (await fileExists(candidatePath)) {
      return pathToFileURL(candidatePath).href;
    }
  }

  return null;
}

async function resolveWorkspacePackageImport(
  authSource: ResolvedAuthSource,
  moduleSpecifier: string
): Promise<string | null> {
  const { packageName } = splitPackageSpecifier(moduleSpecifier);
  const workspacePackage = await findWorkspacePackage(authSource, packageName);
  if (!workspacePackage) {
    return null;
  }
  return await resolvePackageImportFromDescriptor(
    workspacePackage,
    moduleSpecifier
  );
}

async function findInstalledPackage(
  authSource: ResolvedAuthSource,
  packageName: string
): Promise<PackageDescriptor | null> {
  let currentDir = path.dirname(authSource.absolutePath);
  const packagePathSegments = packageName.split("/");

  while (true) {
    const packageDir = path.join(
      currentDir,
      "node_modules",
      ...packagePathSegments
    );
    const packageJsonPath = path.join(packageDir, "package.json");
    if (await fileExists(packageJsonPath)) {
      const packageJson = JSON.parse(
        await readFile(packageJsonPath, "utf8")
      ) as Record<string, unknown>;
      return {
        dir: packageDir,
        name: packageName,
        packageJson,
      };
    }

    const parentDir = path.dirname(currentDir);
    if (parentDir === currentDir) {
      return null;
    }
    currentDir = parentDir;
  }
}

async function resolveInstalledPackageImport(
  authSource: ResolvedAuthSource,
  moduleSpecifier: string
): Promise<string | null> {
  const { packageName } = splitPackageSpecifier(moduleSpecifier);
  const installedPackage = await findInstalledPackage(authSource, packageName);
  if (!installedPackage) {
    return null;
  }
  return await resolvePackageImportFromDescriptor(
    installedPackage,
    moduleSpecifier
  );
}

function isGeneratedFile(content: string): boolean {
  return content.startsWith(GENERATED_MARKER);
}

async function resolveAuthSource(cwd: string): Promise<ResolvedAuthSource | null> {
  const definitionPath = path.join(cwd, "convex", "zen.config.ts");
  if (await fileExists(definitionPath)) {
    return {
      absolutePath: definitionPath,
      relativePath: path.join("convex", "zen.config.ts"),
    };
  }

  return null;
}

function hasOAuthProviders(authSource: string): boolean {
  // Strip block and line comments so that commented-out providers are not detected.
  // Note: this regex-based stripping does not account for comment-like sequences
  // inside string literals, which is an acceptable limitation for zen.config.ts files.
  const stripped = authSource
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/\/\/[^\n]*/g, "");

  // Locate the opening parenthesis of the defineConvexZen(...) call.
  const callMatch = stripped.match(/defineConvexZen\s*\(/);
  if (!callMatch || callMatch.index === undefined) return false;

  // Walk forward tracking parenthesis depth to extract only the call's arguments,
  // avoiding false positives from any `providers:` that appears outside this call.
  let depth = 1;
  let i = callMatch.index + callMatch[0].length;
  while (i < stripped.length && depth > 0) {
    const ch = stripped[i];
    if (ch === "(") depth++;
    else if (ch === ")") depth--;
    i++;
  }

  const callContent = stripped.slice(callMatch.index + callMatch[0].length, i - 1);
  return /\bproviders\s*:/.test(callContent);
}

type ImportedBinding = {
  importedName: string;
  moduleSpecifier: string;
};

function parseNamedImports(authSource: string): Map<string, ImportedBinding> {
  const bindings = new Map<string, ImportedBinding>();
  const importPattern =
    /import\s*\{([^}]+)\}\s*from\s*["']([^"']+)["'];?/g;
  let match = importPattern.exec(authSource);
  while (match) {
    const specifiers = match[1]?.split(",") ?? [];
    const moduleSpecifier = match[2];
    for (const specifier of specifiers) {
      const trimmed = specifier.trim();
      if (!trimmed || !moduleSpecifier) {
        continue;
      }
      const [importedName, localName] = trimmed.split(/\s+as\s+/);
      const resolvedImportedName = importedName?.trim();
      const resolvedLocalName = (localName ?? importedName)?.trim();
      if (!resolvedImportedName || !resolvedLocalName) {
        continue;
      }
      bindings.set(resolvedLocalName, {
        importedName: resolvedImportedName,
        moduleSpecifier,
      });
    }
    match = importPattern.exec(authSource);
  }
  return bindings;
}

function detectConfiguredPluginFactories(authSource: string): string[] {
  const pluginsMatch = authSource.match(/plugins\s*:\s*\[([\s\S]*?)\]/m);
  if (!pluginsMatch?.[1]) {
    return [];
  }
  const uncommentedPluginsSource = pluginsMatch[1]
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/^\s*\/\/.*$/gm, "");
  const factoryIds: string[] = [];
  const callPattern = /([A-Za-z0-9_]+)\s*\(/g;
  let match = callPattern.exec(uncommentedPluginsSource);
  while (match) {
    if (match[1]) {
      factoryIds.push(match[1]);
    }
    match = callPattern.exec(uncommentedPluginsSource);
  }
  return factoryIds;
}

async function importPluginDefinition(
  authSource: ResolvedAuthSource,
  binding: ImportedBinding
): Promise<PluginDefinition> {
  const moduleSpecifier = await resolveImportSpecifier(authSource, binding.moduleSpecifier);
  const moduleNamespace = (await import(moduleSpecifier)) as Record<string, unknown>;
  const pluginFactory = moduleNamespace[binding.importedName] as {
    definition?: PluginDefinition;
  };
  if (!pluginFactory?.definition) {
    throw new Error(
      `Plugin factory "${binding.importedName}" from "${binding.moduleSpecifier}" does not expose static definition metadata.`
    );
  }
  return pluginFactory.definition;
}

function toGeneratedImportPath(
  sourceFileAbsolutePath: string,
  targetFileAbsolutePath: string
): string {
  const relativeImport = path.relative(
    path.dirname(sourceFileAbsolutePath),
    targetFileAbsolutePath
  );
  const normalized = relativeImport.replace(/\\/g, "/").replace(/\.ts$/, "");
  return normalized.startsWith(".") ? normalized : `./${normalized}`;
}

async function resolveGeneratedComponentImportPath(
  authSource: ResolvedAuthSource,
  pluginModuleSpecifier: string,
  pluginDefinition: PluginDefinition
): Promise<string> {
  if (!pluginModuleSpecifier.startsWith(".") && !path.isAbsolute(pluginModuleSpecifier)) {
    return `${pluginModuleSpecifier}/convex.config`;
  }
  if (pluginModuleSpecifier.startsWith("convex-zen/plugins/")) {
    return `${pluginModuleSpecifier}/convex.config`;
  }
  const pluginModulePath = await resolvePluginModulePath(authSource, pluginModuleSpecifier);
  if (!pluginModulePath) {
    throw new Error(
      `Could not resolve plugin module path for "${pluginDefinition.id}" from "${pluginModuleSpecifier}".`
    );
  }
  if (
    pluginModulePath.includes(`${path.sep}src${path.sep}client${path.sep}plugins${path.sep}`) ||
    pluginModulePath.includes(`${path.sep}src${path.sep}plugins${path.sep}`)
  ) {
    return `convex-zen/plugins/${pluginDefinition.id}/convex.config`;
  }
  const componentAbsolutePath = path.resolve(
    path.dirname(pluginModulePath),
    "convex.config.ts"
  );
  return toGeneratedImportPath(
    path.join(path.dirname(authSource.absolutePath), "zen", "component", "convex.config.ts"),
    componentAbsolutePath
  );
}

async function resolveGatewaySourcePath(
  authSource: ResolvedAuthSource,
  pluginModuleSpecifier: string,
  pluginDefinition: PluginDefinition
): Promise<string> {
  if (!pluginModuleSpecifier.startsWith(".") && !path.isAbsolute(pluginModuleSpecifier)) {
    return `${pluginModuleSpecifier}/gateway`;
  }
  if (pluginModuleSpecifier.startsWith("convex-zen/plugins/")) {
    return `${pluginModuleSpecifier}/gateway`;
  }
  const pluginModulePath = await resolvePluginModulePath(authSource, pluginModuleSpecifier);
  if (!pluginModulePath) {
    throw new Error(
      `Could not resolve plugin module path for "${pluginDefinition.id}" from "${pluginModuleSpecifier}".`
    );
  }
  if (
    pluginModulePath.includes(`${path.sep}src${path.sep}client${path.sep}plugins${path.sep}`) ||
    pluginModulePath.includes(`${path.sep}src${path.sep}plugins${path.sep}`)
  ) {
    return `convex-zen/plugins/${pluginDefinition.id}/gateway`;
  }
  return path.resolve(path.dirname(pluginModulePath), "gateway.ts");
}

async function resolvePluginModulePath(
  authSource: ResolvedAuthSource,
  pluginModuleSpecifier: string
): Promise<string | null> {
  if (path.isAbsolute(pluginModuleSpecifier)) {
    return pluginModuleSpecifier;
  }
  if (!pluginModuleSpecifier.startsWith(".")) {
    if (pluginModuleSpecifier === "convex-zen") {
      return null;
    }
    const moduleSpecifier = await resolveImportSpecifier(authSource, pluginModuleSpecifier);
    return moduleSpecifier.startsWith("file:")
      ? fileURLToPath(moduleSpecifier)
      : null;
  }
  const resolved = path.resolve(path.dirname(authSource.absolutePath), pluginModuleSpecifier);
  if (await fileExists(resolved)) {
    const resolvedStats = await stat(resolved);
    if (resolvedStats.isFile()) {
      return resolved;
    }
  }
  const indexPath = path.join(resolved, "index.ts");
  if (await fileExists(indexPath)) {
    return indexPath;
  }
  const directTsPath = `${resolved}.ts`;
  if (await fileExists(directTsPath)) {
    return directTsPath;
  }
  return resolved;
}

async function resolveImportSpecifier(
  authSource: ResolvedAuthSource,
  moduleSpecifier: string
): Promise<string> {
  if (moduleSpecifier.startsWith(".")) {
    return pathToFileURL(
      path.resolve(path.dirname(authSource.absolutePath), moduleSpecifier)
    ).href;
  }
  if (moduleSpecifier === "convex-zen") {
    const workspaceRoot = await findWorkspaceRoot(path.dirname(authSource.absolutePath));
    if (workspaceRoot) {
      return pathToFileURL(
        path.join(workspaceRoot, "packages", "convex-zen", "src", "client", "index.ts")
      ).href;
    }
  }
  if (moduleSpecifier.startsWith("convex-zen/")) {
    const workspaceRoot = await findWorkspaceRoot(path.dirname(authSource.absolutePath));
    if (workspaceRoot) {
      const subpath = moduleSpecifier.slice("convex-zen/".length);
      const mapped = subpath === "component"
        ? path.join(workspaceRoot, "packages", "convex-zen", "src", "component", "index.ts")
        : subpath === "convex.config"
          ? path.join(workspaceRoot, "packages", "convex-zen", "src", "component", "convex.config.ts")
            : subpath === "core/convex.config"
              ? path.join(workspaceRoot, "packages", "convex-zen", "src", "component", "core", "convex.config.ts")
            : subpath.startsWith("plugins/") && subpath.endsWith("/convex.config")
              ? path.join(
                  workspaceRoot,
                  "packages",
                  "convex-zen",
                  "src",
                  "plugins",
                  subpath.replace(/^plugins\//, "").replace(/\/convex\.config$/, ""),
                  "convex.config.ts"
                )
              : subpath.startsWith("plugins/") && subpath.endsWith("/gateway")
                ? path.join(
                    workspaceRoot,
                    "packages",
                    "convex-zen",
                    "src",
                    "plugins",
                    subpath.replace(/^plugins\//, "").replace(/\/gateway$/, ""),
                    "gateway.ts"
                  )
              : path.join(workspaceRoot, "packages", "convex-zen", "src", "client", `${subpath}.ts`);
      if (await fileExists(mapped)) {
        return pathToFileURL(mapped).href;
      }
    }
  }
  if (!moduleSpecifier.startsWith(".")) {
    const workspaceImport = await resolveWorkspacePackageImport(
      authSource,
      moduleSpecifier
    );
    if (workspaceImport) {
      return workspaceImport;
    }
    const installedImport = await resolveInstalledPackageImport(
      authSource,
      moduleSpecifier
    );
    if (installedImport) {
      return installedImport;
    }
    const resolved = nodeRequire.resolve(moduleSpecifier, {
      paths: [path.dirname(authSource.absolutePath)],
    });
    return pathToFileURL(resolved).href;
  }
  return moduleSpecifier;
}

async function findWorkspaceRoot(startDir: string): Promise<string | null> {
  let currentDir = startDir;
  while (true) {
    const candidate = path.join(currentDir, "packages", "convex-zen", "package.json");
    if (await fileExists(candidate)) {
      return currentDir;
    }
    const parentDir = path.dirname(currentDir);
    if (parentDir === currentDir) {
      return null;
    }
    currentDir = parentDir;
  }
}

async function loadPluginDefinitions(
  authSource: ResolvedAuthSource,
  authSourceContents: string
): Promise<LoadedPluginDefinition[]> {
  const imports = parseNamedImports(authSourceContents);
  const factoryIds = detectConfiguredPluginFactories(authSourceContents);
  const definitions: LoadedPluginDefinition[] = [];
  for (const factoryId of factoryIds) {
    const binding = imports.get(factoryId);
    if (!binding) {
      throw new Error(
        `Could not resolve plugin factory "${factoryId}" from ${authSource.relativePath}.`
      );
    }
    const definition = await importPluginDefinition(authSource, binding);
    const gatewayFunctions = collectPluginGatewayMetadata(definition.gateway);
    definitions.push({
      definition,
      componentImportPath: await resolveGeneratedComponentImportPath(
        authSource,
        binding.moduleSpecifier,
        definition
      ),
      gatewaySourcePath: await resolveGatewaySourcePath(
        authSource,
        binding.moduleSpecifier,
        definition
      ),
      childName: `${definition.id}Component`,
      gatewayFunctions,
    });
  }
  return definitions;
}

function sanitizeIdentifier(value: string): string {
  const sanitized = value.replace(/[^A-Za-z0-9_]/g, "_");
  return /^[A-Za-z_]/.test(sanitized) ? sanitized : `plugin_${sanitized}`;
}

function renderAuthComponentConfigFile(
  pluginDefinitions: LoadedPluginDefinition[]
): string {
  const imports = [
    'import { defineComponent } from "convex/server";',
    'import core from "convex-zen/core/convex.config";',
    ...pluginDefinitions.map(
      (plugin) =>
        `import ${sanitizeIdentifier(plugin.childName)} from ${JSON.stringify(
          plugin.componentImportPath
        )};`
    ),
  ];
  const uses = [
    'zenComponent.use(core, { name: "core" });',
    ...pluginDefinitions.map(
      (plugin) =>
        `zenComponent.use(${sanitizeIdentifier(plugin.childName)}, { name: ${JSON.stringify(
          plugin.childName
        )} });`
    ),
  ];

  return normalizeContent(`${GENERATED_MARKER}
${imports.join("\n")}

const zenComponent = defineComponent("zenComponent");

${uses.join("\n")}

export default zenComponent;
`);
}

function renderComponentRuntimeFile(
  pluginDefinitions: LoadedPluginDefinition[],
  zenConfigImportPath: string
): string {
  const componentChildren = [
    "  core: components.core,",
    ...pluginDefinitions.map(
      (plugin) =>
        `  ${JSON.stringify(plugin.childName)}: components[${JSON.stringify(plugin.childName)}],`
    ),
  ].join("\n");

  return normalizeContent(`${GENERATED_MARKER}
import { components } from "./_generated/api";
import { createConvexZenClient } from "convex-zen";
import zenConfig from ${JSON.stringify(zenConfigImportPath)};

const runtimeComponent = {
${componentChildren}
} as const;

export const auth = createConvexZenClient(
  runtimeComponent as Record<string, unknown>,
  zenConfig,
  { runtimeKind: "component" }
);
`);
}

function renderAppRuntimeFile(): string {
  return normalizeContent(`${GENERATED_MARKER}
import { components } from "../_generated/api";
import { createConvexZenClient } from "convex-zen";
import zenConfig from "../zen.config";

export const auth = createConvexZenClient(
  components.zenComponent as Record<string, unknown>,
  zenConfig,
  { runtimeKind: "app" }
);
`);
}

function renderZenGatewayFile(options: {
  includeOAuth: boolean;
}): string {
  const serverImports = options.includeOAuth
    ? "action, mutation, query"
    : "mutation, query";
  const oauthExports = options.includeOAuth
    ? `
export const getAuthorizationUrl = mutation({
  args: {
    provider: v.object({
      id: v.string(),
      clientId: v.string(),
      clientSecret: v.string(),
      authorizationUrl: v.string(),
      tokenUrl: v.string(),
      userInfoUrl: v.string(),
      scopes: v.array(v.string()),
      trustVerifiedEmail: v.optional(v.boolean()),
      tokenEncryptionSecret: v.optional(v.string()),
    }),
    callbackUrl: v.optional(v.string()),
    redirectTo: v.optional(v.string()),
    errorRedirectTo: v.optional(v.string()),
    redirectUrl: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return ctx.runMutation(components.core.gateway.getAuthorizationUrl, args);
  },
});

export const handleCallback = action({
  args: {
    provider: v.object({
      id: v.string(),
      clientId: v.string(),
      clientSecret: v.string(),
      authorizationUrl: v.string(),
      tokenUrl: v.string(),
      userInfoUrl: v.string(),
      scopes: v.array(v.string()),
      trustVerifiedEmail: v.optional(v.boolean()),
      tokenEncryptionSecret: v.optional(v.string()),
    }),
    code: v.string(),
    state: v.string(),
    callbackUrl: v.optional(v.string()),
    redirectTo: v.optional(v.string()),
    errorRedirectTo: v.optional(v.string()),
    redirectUrl: v.optional(v.string()),
    ipAddress: v.optional(v.string()),
    userAgent: v.optional(v.string()),
    defaultRole: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return ctx.runAction(components.core.gateway.handleCallback, args);
  },
});
`
    : "";

  return normalizeContent(`${GENERATED_MARKER}
import { v } from "convex/values";
import { ${serverImports} } from "./_generated/server";
import { components } from "./_generated/api";

export const signUp = mutation({
  args: {
    email: v.string(),
    password: v.string(),
    name: v.optional(v.string()),
    ipAddress: v.optional(v.string()),
    defaultRole: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return ctx.runMutation(components.core.gateway.signUp, args);
  },
});

export const signIn = mutation({
  args: {
    email: v.string(),
    password: v.string(),
    ipAddress: v.optional(v.string()),
    userAgent: v.optional(v.string()),
    requireEmailVerified: v.optional(v.boolean()),
  },
  handler: async (ctx, args) => {
    return ctx.runMutation(components.core.gateway.signIn, args);
  },
});

export const verifyEmail = mutation({
  args: {
    email: v.string(),
    code: v.string(),
  },
  handler: async (ctx, args) => {
    return ctx.runMutation(components.core.gateway.verifyEmail, args);
  },
});

export const requestPasswordReset = mutation({
  args: {
    email: v.string(),
    ipAddress: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return ctx.runMutation(components.core.gateway.requestPasswordReset, args);
  },
});

export const resetPassword = mutation({
  args: {
    email: v.string(),
    code: v.string(),
    newPassword: v.string(),
  },
  handler: async (ctx, args) => {
    return ctx.runMutation(components.core.gateway.resetPassword, args);
  },
});

export const validateSession = mutation({
  args: {
    token: v.string(),
    checkBanned: v.optional(v.boolean()),
  },
  handler: async (ctx, args) => {
    return ctx.runMutation(components.core.gateway.validateSession, args);
  },
});

export const getCurrentUser = query({
  args: {
    token: v.string(),
    checkBanned: v.optional(v.boolean()),
  },
  handler: async (ctx, args) => {
    return ctx.runQuery(components.core.gateway.getCurrentUser, args);
  },
});

export const getUserById = query({
  args: {
    userId: v.string(),
    checkBanned: v.optional(v.boolean()),
  },
  handler: async (ctx, args) => {
    return ctx.runQuery(components.core.gateway.getUserById, args);
  },
});

export const invalidateSession = mutation({
  args: {
    token: v.string(),
  },
  handler: async (ctx, args) => {
    return ctx.runMutation(components.core.gateway.invalidateSession, args);
  },
});

export const invalidateAllSessions = mutation({
  args: {
    userId: v.string(),
  },
  handler: async (ctx, args) => {
    return ctx.runMutation(components.core.gateway.invalidateAllSessions, args);
  },
});

${oauthExports}
`);
}

function renderCoreWrapperFile(options: {
  includeOAuth: boolean;
}): string {
  const serverImports = options.includeOAuth
    ? "action, mutation, query"
    : "mutation, query";
  const oauthExports = options.includeOAuth
    ? `
export const getOAuthUrl = mutation({
  args: {
    providerId: v.string(),
    callbackUrl: v.optional(v.string()),
    redirectTo: v.optional(v.string()),
    errorRedirectTo: v.optional(v.string()),
    redirectUrl: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return auth.getOAuthUrl(ctx, args.providerId, {
      callbackUrl: args.callbackUrl,
      redirectTo: args.redirectTo,
      errorRedirectTo: args.errorRedirectTo,
      redirectUrl: args.redirectUrl,
    });
  },
});

export const handleOAuthCallback = action({
  args: {
    providerId: v.string(),
    code: v.string(),
    state: v.string(),
    callbackUrl: v.optional(v.string()),
    redirectTo: v.optional(v.string()),
    errorRedirectTo: v.optional(v.string()),
    redirectUrl: v.optional(v.string()),
    ipAddress: v.optional(v.string()),
    userAgent: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return auth.handleCallback(ctx, args);
  },
});
`
    : "";

  return normalizeContent(`${GENERATED_MARKER}
import { v } from "convex/values";
import { ${serverImports} } from "../_generated/server";
import { auth } from "./_generated/auth";

export const signUp = mutation({
  args: {
    email: v.string(),
    password: v.string(),
    name: v.optional(v.string()),
    ipAddress: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return auth.signUp(ctx, args);
  },
});

export const signInWithEmail = mutation({
  args: {
    email: v.string(),
    password: v.string(),
    ipAddress: v.optional(v.string()),
    userAgent: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return auth.signIn(ctx, args);
  },
});

export const verifyEmail = mutation({
  args: {
    email: v.string(),
    code: v.string(),
  },
  handler: async (ctx, args) => {
    return auth.verifyEmail(ctx, args);
  },
});

export const requestPasswordReset = mutation({
  args: {
    email: v.string(),
    ipAddress: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return auth.requestPasswordReset(ctx, args);
  },
});

export const resetPassword = mutation({
  args: {
    email: v.string(),
    code: v.string(),
    newPassword: v.string(),
  },
  handler: async (ctx, args) => {
    return auth.resetPassword(ctx, args);
  },
});

export const invalidateSession = mutation({
  args: {
    token: v.string(),
  },
  handler: async (ctx, args) => {
    await auth.signOut(ctx, args.token);
  },
});

export const invalidateAllSessions = mutation({
  args: {
    userId: v.string(),
  },
  handler: async (ctx, args) => {
    await auth.signOutAll(ctx, args.userId);
  },
});

export const validateSession = mutation({
  args: {
    token: v.string(),
  },
  handler: async (ctx, args) => {
    return auth.session.validate(ctx, args.token);
  },
});

export const currentUser = query({
  args: {
    token: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return auth.user.safeGet(ctx, args.token);
  },
});

export const getUserById = query({
  args: {
    userId: v.string(),
  },
  handler: async (ctx, args) => {
    return auth.getAuthUserById(ctx, args.userId);
  },
});

${oauthExports}
`);
}

function resolveGatewayImportPathForGeneratedFile(
  generatedFileAbsolutePath: string,
  gatewaySourcePath: string
): string {
  return gatewaySourcePath.startsWith("/")
    ? toGeneratedImportPath(generatedFileAbsolutePath, gatewaySourcePath)
    : gatewaySourcePath;
}

function renderPluginFacadeFile(options: {
  pluginDefinition: PluginDefinition;
  gatewayFunctions: PluginGatewayRuntimeMethods;
  gatewayImportPath: string;
  serverImportPath: string;
  runtimeImportPath: string;
  runtimeImportName?: string;
}): string {
  const pluginName = options.pluginDefinition.id;
  const kinds = new Set(
    Object.values(options.gatewayFunctions).map((fn) => fn.kind)
  );
  const serverImports = [...kinds].sort().join(", ");
  const functionSource = Object.entries(options.gatewayFunctions)
    .map(([functionName, fn]) => {
      const runtimeAccess = `auth.plugins.${pluginName}.${functionName}`;
      return `export const ${functionName} = ${fn.kind}({
  args: getPublicPluginFunctionArgs(pluginGateway.${functionName}, ${JSON.stringify(functionName)}),
  handler: async (ctx, args) => {
    return ${runtimeAccess}(ctx, args);
  },
});`;
    })
    .join("\n\n");

  const runtimeImportName = options.runtimeImportName ?? "auth";
  const runtimeImport =
    runtimeImportName === "auth"
      ? `import { auth } from ${JSON.stringify(options.runtimeImportPath)};`
      : `import { ${runtimeImportName} as auth } from ${JSON.stringify(options.runtimeImportPath)};`;

  return normalizeContent(`${GENERATED_MARKER}
import { ${serverImports} } from ${JSON.stringify(options.serverImportPath)};
import { getPublicPluginFunctionArgs } from "convex-zen/component";
import * as pluginGateway from ${JSON.stringify(options.gatewayImportPath)};
${runtimeImport}

${functionSource}
`);
}

function renderCoreFile(options: {
  includeOAuth: boolean;
}): string {
  const serverImports = options.includeOAuth
    ? "action, mutation, query"
    : "mutation, query";
  const componentHelper = options.includeOAuth
    ? `
function componentFn<TKind extends "query" | "mutation" | "action">(
  path: string
): import("convex/server").FunctionReference<TKind, "public" | "internal"> {
  const [modulePath, funcName] = path.split(":");
  if (!modulePath || !funcName) {
    throw new Error(\`Invalid function path: \${path}\`);
  }
  const parts = modulePath.split("/");
  let ref: Record<string, unknown> = components.zenComponent as Record<string, unknown>;
  for (const part of parts) {
    const next = ref[part];
    if (!next || (typeof next !== "object" && typeof next !== "function")) {
      throw new Error(\`Invalid function path segment: \${part}\`);
    }
    ref = next as Record<string, unknown>;
  }
  const resolved = ref[funcName];
  if (!resolved) {
    throw new Error(\`Function not found: \${path}\`);
  }
  return resolved as import("convex/server").FunctionReference<
    TKind,
    "public" | "internal"
  >;
}
`
    : "";
  const oauthExports = options.includeOAuth
    ? `
export const getOAuthUrl = mutation({
  args: {
    providerId: v.string(),
    callbackUrl: v.optional(v.string()),
    redirectTo: v.optional(v.string()),
    errorRedirectTo: v.optional(v.string()),
    redirectUrl: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const provider = resolveOAuthProvider(args.providerId);
    if (!provider) {
      throw new Error(\`OAuth provider "\${args.providerId}" not configured\`);
    }
    return ctx.runMutation(componentFn<"mutation">("core/gateway:getAuthorizationUrl"), {
      provider,
      callbackUrl: args.callbackUrl,
      redirectTo: args.redirectTo,
      errorRedirectTo: args.errorRedirectTo,
      redirectUrl: args.redirectUrl,
    });
  },
});

export const handleOAuthCallback = action({
  args: {
    providerId: v.string(),
    code: v.string(),
    state: v.string(),
    callbackUrl: v.optional(v.string()),
    redirectTo: v.optional(v.string()),
    errorRedirectTo: v.optional(v.string()),
    redirectUrl: v.optional(v.string()),
    ipAddress: v.optional(v.string()),
    userAgent: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const provider = resolveOAuthProvider(args.providerId);
    if (!provider) {
      throw new Error(\`OAuth provider "\${args.providerId}" not configured\`);
    }
    return ctx.runAction(componentFn<"action">("core/gateway:handleCallback"), {
      provider,
      code: args.code,
      state: args.state,
      callbackUrl: args.callbackUrl,
      redirectTo: args.redirectTo,
      errorRedirectTo: args.errorRedirectTo,
      redirectUrl: args.redirectUrl,
      ipAddress: args.ipAddress,
      userAgent: args.userAgent,
      defaultRole: resolveDefaultRole(),
    });
  },
});
`
    : "";

  return normalizeContent(`${GENERATED_MARKER}
import { v } from "convex/values";
import { ${serverImports} } from "../_generated/server";
${options.includeOAuth ? 'import { components } from "../_generated/api";\n' : ""}import { auth } from "./_generated/auth";
${options.includeOAuth ? 'import { resolveDefaultRole, resolveOAuthProvider } from "./_generated/oauth";\n' : ""}

${componentHelper}
export const signUp = mutation({
  args: {
    email: v.string(),
    password: v.string(),
    name: v.optional(v.string()),
    ipAddress: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return auth.signUp(ctx, args);
  },
});

export const signInWithEmail = mutation({
  args: {
    email: v.string(),
    password: v.string(),
    ipAddress: v.optional(v.string()),
    userAgent: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return auth.signIn(ctx, args);
  },
});

export const verifyEmail = mutation({
  args: {
    email: v.string(),
    code: v.string(),
  },
  handler: async (ctx, args) => {
    return auth.verifyEmail(ctx, args);
  },
});

export const requestPasswordReset = mutation({
  args: {
    email: v.string(),
    ipAddress: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return auth.requestPasswordReset(ctx, args);
  },
});

export const resetPassword = mutation({
  args: {
    email: v.string(),
    code: v.string(),
    newPassword: v.string(),
  },
  handler: async (ctx, args) => {
    return auth.resetPassword(ctx, args);
  },
});

export const invalidateSession = mutation({
  args: {
    token: v.string(),
  },
  handler: async (ctx, args) => {
    await auth.signOut(ctx, args.token);
  },
});

export const validateSession = mutation({
  args: {
    token: v.string(),
  },
  handler: async (ctx, args) => {
    return auth.session.validate(ctx, args.token);
  },
});

export const currentUser = query({
  args: {
    token: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return auth.user.safeGet(ctx, args.token);
  },
});

${oauthExports}
`);
}

function parseFunctionKinds(source: string): Record<string, AuthFunctionKind> {
  const result: Record<string, AuthFunctionKind> = {};
  const pattern = /export\s+const\s+([A-Za-z0-9_]+)\s*=\s*(query|mutation|action)\s*\(/g;
  let match = pattern.exec(source);
  while (match) {
    const functionName = match[1];
    const functionKind = match[2] as AuthFunctionKind;
    if (functionName) {
      result[functionName] = functionKind;
    }
    match = pattern.exec(source);
  }
  return result;
}

function parseExportedFunctionNames(source: string): Set<string> {
  const names = new Set<string>();
  const pattern = /export\s+const\s+([A-Za-z0-9_]+)\s*=/g;
  let match = pattern.exec(source);
  while (match) {
    if (match[1]) {
      names.add(match[1]);
    }
    match = pattern.exec(source);
  }
  return names;
}

function assertNoReservedCoreFunctionNames(source: string): void {
  const exportedNames = parseExportedFunctionNames(source);
  const conflicts: string[] = [];
  for (const reservedName of RESERVED_CORE_FUNCTION_NAMES) {
    if (exportedNames.has(reservedName)) {
      conflicts.push(reservedName);
    }
  }
  if (conflicts.length === 0) {
    return;
  }
  throw new Error(
    `Generated core wrappers include reserved auth-client names: ${conflicts.join(", ")}. ` +
      "Rename core wrappers to non-reserved names."
  );
}

function renderAuthHelperFile(): string {
  return normalizeContent(`${GENERATED_MARKER}
import { components } from "../../_generated/api";
import { createConvexZenClient } from "convex-zen";
import zenConfig from "../../zen.config";

export const auth = createConvexZenClient(
  components.zenComponent as Record<string, unknown>,
  zenConfig,
  { runtimeKind: "app" }
);
`);
}

function renderOAuthHelperFile(): string {
  return normalizeContent(`${GENERATED_MARKER}
import zenConfig from "../../zen.config";

function resolveTokenEncryptionSecret(): string | undefined {
  const explicit = zenConfig.tokenEncryptionSecret?.trim();
  if (explicit && explicit.length > 0) {
    return explicit;
  }
  const envVar = zenConfig.tokenEncryptionSecretEnvVar ?? "CONVEX_ZEN_SECRET";
  const env = (globalThis as { process?: { env?: Record<string, string | undefined> } }).process?.env;
  const fromEnv = env?.[envVar]?.trim();
  return fromEnv && fromEnv.length > 0 ? fromEnv : undefined;
}

const oauthProviders = (zenConfig.providers ?? []).map((provider) => {
  if (provider.tokenEncryptionSecret !== undefined) {
    return provider;
  }
  const tokenEncryptionSecret = resolveTokenEncryptionSecret();
  if (!tokenEncryptionSecret) {
    return provider;
  }
  return {
    ...provider,
    tokenEncryptionSecret,
  };
});

export function resolveOAuthProvider(providerId: string) {
  return oauthProviders.find((provider) => provider.id === providerId);
}

export function resolveDefaultRole(): string | undefined {
  for (const plugin of zenConfig.plugins ?? []) {
    const role = plugin.definition.hooks?.onUserCreated?.defaultRole?.(
      plugin.options,
    );
    if (role !== undefined) {
      const trimmed = role.trim();
      return trimmed.length > 0 ? trimmed : undefined;
    }
  }
  return undefined;
}
`);
}

function renderMetaHelperFile(
  coreMeta: CoreFunctionMeta,
  pluginMeta: PluginFunctionMeta
): string {
  const normalizedCore = Object.fromEntries(
    Object.entries(coreMeta).sort(([a], [b]) => a.localeCompare(b))
  );
  const normalizedPluginEntries = Object.entries(pluginMeta)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([pluginName, functions]) => {
      const sortedFunctions = Object.fromEntries(
        Object.entries(functions).sort(([a], [b]) => a.localeCompare(b))
      );
      return [pluginName, sortedFunctions] as const;
    });
  const normalizedPlugin = Object.fromEntries(normalizedPluginEntries);
  return normalizeContent(`${GENERATED_MARKER}
export const authMeta = ${JSON.stringify(
    {
      core: normalizedCore,
      plugin: normalizedPlugin,
    },
    null,
    2
  )} as const;

export const authCoreMeta = authMeta.core;
export const authPluginMeta = authMeta.plugin;

export type AuthMeta = typeof authMeta;
export type AuthCoreMeta = typeof authCoreMeta;
export type AuthPluginMeta = typeof authPluginMeta;
`);
}

async function upsertGeneratedFile(
  file: GeneratedFile,
  options: GenerateOptions,
  result: GenerateResult
): Promise<void> {
  const exists = await fileExists(file.absolutePath);
  if (!exists) {
    if (options.check) {
      result.updated.push(file.relativePath);
      return;
    }
    await mkdir(path.dirname(file.absolutePath), { recursive: true });
    await writeFile(file.absolutePath, file.content, "utf8");
    result.created.push(file.relativePath);
    return;
  }

  const existing = await readFile(file.absolutePath, "utf8");
  if (!isGeneratedFile(existing)) {
    throw new Error(
      `Refusing to overwrite non-generated file: ${file.relativePath}`
    );
  }

  if (existing === file.content) {
    result.unchanged.push(file.relativePath);
    return;
  }

  if (options.check) {
    result.updated.push(file.relativePath);
    return;
  }

  await writeFile(file.absolutePath, file.content, "utf8");
  result.updated.push(file.relativePath);
}

async function deleteGeneratedFileIfExists(
  absolutePath: string,
  relativePath: string,
  options: GenerateOptions,
  result: GenerateResult
): Promise<void> {
  if (!(await fileExists(absolutePath))) {
    return;
  }
  const existing = await readFile(absolutePath, "utf8");
  if (!isGeneratedFile(existing)) {
    throw new Error(`Refusing to delete non-generated file: ${relativePath}`);
  }
  if (options.check) {
    result.deleted.push(relativePath);
    return;
  }
  await rm(absolutePath);
  result.deleted.push(relativePath);
}

async function deleteGeneratedTreeIfExists(
  absoluteDir: string,
  relativeDir: string,
  options: GenerateOptions,
  result: GenerateResult
): Promise<void> {
  if (!(await fileExists(absoluteDir))) {
    return;
  }
  const entries = await readdir(absoluteDir, { withFileTypes: true });
  for (const entry of entries) {
    const absolutePath = path.join(absoluteDir, entry.name);
    const relativePath = path.join(relativeDir, entry.name);
    if (entry.isDirectory()) {
      await deleteGeneratedTreeIfExists(
        absolutePath,
        relativePath,
        options,
        result
      );
      continue;
    }
    const existing = await readFile(absolutePath, "utf8");
    if (!isGeneratedFile(existing)) {
      if (relativePath.includes(`${path.sep}_generated${path.sep}`)) {
        if (options.check) {
          result.deleted.push(relativePath);
          continue;
        }
        await rm(absolutePath);
        result.deleted.push(relativePath);
        continue;
      }
      result.warnings.push(
        `Skipped non-generated legacy file during generated auth cleanup: ${relativePath}`
      );
      continue;
    }
    if (options.check) {
      result.deleted.push(relativePath);
      continue;
    }
    await rm(absolutePath);
    result.deleted.push(relativePath);
  }
}

export async function generateAuthFunctions(
  options: GenerateOptions
): Promise<GenerateResult> {
  const result: GenerateResult = {
    created: [],
    updated: [],
    deleted: [],
    unchanged: [],
    warnings: [],
  };

  const zenDir = path.join(options.cwd, "convex", "zen");
  const zenGeneratedDir = path.join(zenDir, "_generated");
  const pluginDir = path.join(zenDir, "plugin");
  const componentDir = path.join(zenDir, "component");
  const legacyAuthDir = path.join(options.cwd, "convex", "auth");
  const legacyAuthComponentDir = path.join(options.cwd, "convex", "authComponent");
  const authSource = await resolveAuthSource(options.cwd);
  if (!authSource) {
    throw new Error(
      `Missing auth source file. Expected ${path.join(
        "convex",
        "zen.config.ts"
      )}`
    );
  }
  const authSourceContents = await readFile(authSource.absolutePath, "utf8");
  const pluginDefinitions = await loadPluginDefinitions(authSource, authSourceContents);
  const includeOAuth = hasOAuthProviders(authSourceContents);
  const coreContent = renderCoreWrapperFile({
    includeOAuth,
  });
  const zenGatewayContent = renderZenGatewayFile({
    includeOAuth,
  });
  assertNoReservedCoreFunctionNames(coreContent);

  const filesToGenerate: GeneratedFile[] = [
    {
      absolutePath: path.join(componentDir, "convex.config.ts"),
      relativePath: path.join("convex", "zen", "component", "convex.config.ts"),
      content: renderAuthComponentConfigFile(pluginDefinitions),
    },
    {
      absolutePath: path.join(zenDir, "core.ts"),
      relativePath: path.join("convex", "zen", "core.ts"),
      content: coreContent,
    },
    {
      absolutePath: path.join(componentDir, "_runtime.ts"),
      relativePath: path.join("convex", "zen", "component", "_runtime.ts"),
      content: renderComponentRuntimeFile(pluginDefinitions, "../../zen.config"),
    },
    {
      absolutePath: path.join(componentDir, "gateway.ts"),
      relativePath: path.join("convex", "zen", "component", "gateway.ts"),
      content: zenGatewayContent,
    },
  ];
  const generatedPluginSources = new Map<string, string>();
  const coreMeta = parseFunctionKinds(coreContent);

  for (const pluginDefinition of pluginDefinitions) {
    const pluginAbsolutePath = path.join(
      pluginDir,
      `${pluginDefinition.definition.id}.ts`
    );
    const pluginContent = renderPluginFacadeFile({
      pluginDefinition: pluginDefinition.definition,
      gatewayFunctions: pluginDefinition.gatewayFunctions,
      gatewayImportPath: resolveGatewayImportPathForGeneratedFile(
        pluginAbsolutePath,
        pluginDefinition.gatewaySourcePath
      ),
      serverImportPath: "../../_generated/server",
      runtimeImportPath: "../_generated/auth",
    });
    filesToGenerate.push({
      absolutePath: pluginAbsolutePath,
      relativePath: path.join(
        "convex",
        "zen",
        "plugin",
        `${pluginDefinition.definition.id}.ts`
      ),
      content: pluginContent,
    });
    generatedPluginSources.set(pluginDefinition.definition.id, pluginContent);
    const componentGatewayAbsolutePath = path.join(
      componentDir,
      pluginDefinition.definition.id,
      "gateway.ts"
    );
    const zenPluginContent = renderPluginFacadeFile({
      pluginDefinition: pluginDefinition.definition,
      gatewayFunctions: pluginDefinition.gatewayFunctions,
      gatewayImportPath: resolveGatewayImportPathForGeneratedFile(
        componentGatewayAbsolutePath,
        pluginDefinition.gatewaySourcePath
      ),
      serverImportPath: "../_generated/server",
      runtimeImportPath: "../_runtime",
    });
    filesToGenerate.push({
      absolutePath: componentGatewayAbsolutePath,
      relativePath: path.join(
        "convex",
        "zen",
        "component",
        pluginDefinition.definition.id,
        "gateway.ts"
      ),
      content: zenPluginContent,
    });
  }

  for (const file of filesToGenerate) {
    await upsertGeneratedFile(file, options, result);
  }

  await deleteGeneratedFileIfExists(
    path.join(zenDir, "admin.ts"),
    path.join("convex", "zen", "admin.ts"),
    options,
    result
  );
  await deleteGeneratedFileIfExists(
    path.join(pluginDir, "admin.ts"),
    path.join("convex", "zen", "plugin", "admin.ts"),
    options,
    result
  );
  await deleteGeneratedFileIfExists(
    path.join(componentDir, "admin", "gateway.ts"),
    path.join("convex", "zen", "component", "admin", "gateway.ts"),
    options,
    result
  );

  const pluginMeta: PluginFunctionMeta = {};
  for (const pluginDefinition of pluginDefinitions) {
    const kinds = Object.fromEntries(
      Object.entries(pluginDefinition.gatewayFunctions).map(
        ([functionName, metadata]) => [functionName, metadata.kind]
      )
    );
    if (Object.keys(kinds).length > 0) {
      pluginMeta[pluginDefinition.definition.id] = kinds;
    }
  }

  if (await fileExists(pluginDir)) {
    const entries = await readdir(pluginDir, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isFile() || !entry.name.endsWith(".ts")) {
        continue;
      }
      if (entry.name === "shared.ts") {
        continue;
      }
      const pluginName = entry.name.slice(0, -3);
      if (generatedPluginSources.has(pluginName)) {
        continue;
      }
      await deleteGeneratedFileIfExists(
        path.join(pluginDir, entry.name),
        path.join("convex", "zen", "plugin", entry.name),
        options,
        result
      );
    }
  }

  if (await fileExists(componentDir)) {
    const entries = await readdir(componentDir, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isDirectory()) {
        continue;
      }
      if (entry.name === "_generated" || entry.name === "plugin") {
        continue;
      }
      if (generatedPluginSources.has(entry.name)) {
        continue;
      }
      await deleteGeneratedFileIfExists(
        path.join(componentDir, entry.name, "gateway.ts"),
        path.join("convex", "zen", "component", entry.name, "gateway.ts"),
        options,
        result
      );
    }
  }

  await upsertGeneratedFile(
    {
      absolutePath: path.join(zenGeneratedDir, "auth.ts"),
      relativePath: path.join("convex", "zen", "_generated", "auth.ts"),
      content: renderAuthHelperFile(),
    },
    options,
    result
  );

  if (includeOAuth) {
    await upsertGeneratedFile(
      {
        absolutePath: path.join(zenGeneratedDir, "oauth.ts"),
        relativePath: path.join("convex", "zen", "_generated", "oauth.ts"),
        content: renderOAuthHelperFile(),
      },
      options,
      result
    );
  } else {
    await deleteGeneratedFileIfExists(
      path.join(zenGeneratedDir, "oauth.ts"),
      path.join("convex", "zen", "_generated", "oauth.ts"),
      options,
      result
    );
  }

  await upsertGeneratedFile(
    {
      absolutePath: path.join(zenGeneratedDir, "meta.ts"),
      relativePath: path.join("convex", "zen", "_generated", "meta.ts"),
      content: renderMetaHelperFile(coreMeta, pluginMeta),
    },
    options,
    result
  );

  await deleteGeneratedFileIfExists(
    path.join(zenDir, "shared.ts"),
    path.join("convex", "zen", "shared.ts"),
    options,
    result
  );

  await deleteGeneratedFileIfExists(
    path.join(zenDir, "_auth.ts"),
    path.join("convex", "zen", "_auth.ts"),
    options,
    result
  );

  await deleteGeneratedFileIfExists(
    path.join(zenDir, "_oauth.ts"),
    path.join("convex", "zen", "_oauth.ts"),
    options,
    result
  );

  await deleteGeneratedFileIfExists(
    path.join(zenDir, "_meta.ts"),
    path.join("convex", "zen", "_meta.ts"),
    options,
    result
  );

  await deleteGeneratedFileIfExists(
    path.join(zenDir, "convex.config.ts"),
    path.join("convex", "zen", "convex.config.ts"),
    options,
    result
  );

  await deleteGeneratedFileIfExists(
    path.join(componentDir, "shared.ts"),
    path.join("convex", "zen", "component", "shared.ts"),
    options,
    result
  );

  await deleteGeneratedFileIfExists(
    path.join(pluginDir, "shared.ts"),
    path.join("convex", "zen", "plugin", "shared.ts"),
    options,
    result
  );

  await deleteGeneratedFileIfExists(
    path.join(zenDir, "_runtime.ts"),
    path.join("convex", "zen", "_runtime.ts"),
    options,
    result
  );

  await deleteGeneratedFileIfExists(
    path.join(zenDir, "gateway.ts"),
    path.join("convex", "zen", "gateway.ts"),
    options,
    result
  );

  await deleteGeneratedTreeIfExists(
    legacyAuthDir,
    path.join("convex", "auth"),
    options,
    result
  );

  await deleteGeneratedTreeIfExists(
    legacyAuthComponentDir,
    path.join("convex", "authComponent"),
    options,
    result
  );

  return result;
}
