// @generated by convex-zen generate. DO NOT EDIT.
import { defineComponent } from "convex/server";
import core from "convex-zen/core/convex.config";
import adminComponent from "convex-zen/plugins/admin/convex.config";
import organizationComponent from "convex-zen/plugins/organization/convex.config";

const zenComponent = defineComponent("zenComponent");

zenComponent.use(core, { name: "core" });
zenComponent.use(adminComponent, { name: "adminComponent" });
zenComponent.use(organizationComponent, { name: "organizationComponent" });

export default zenComponent;
