// @generated by convex-zen generate. DO NOT EDIT.
import { defineComponent } from "convex/server";
import core from "convex-zen/core/convex.config";
import systemAdminComponent from "convex-zen-system-admin/convex.config";
import organizationComponent from "convex-zen-organization/convex.config";

const zenComponent = defineComponent("zenComponent");

zenComponent.use(core, { name: "core" });
zenComponent.use(systemAdminComponent, { name: "systemAdminComponent" });
zenComponent.use(organizationComponent, { name: "organizationComponent" });

export default zenComponent;
