// @generated by convex-zen generate. DO NOT EDIT.
import { defineSchema } from "convex/server";
import { coreSchemaTables } from "convex-zen/component/core-schema-definition";
import { systemAdminPlugin as systemAdminPluginFactory } from "convex-zen/plugins/system-admin";
import { organizationPlugin as organizationPluginFactory } from "convex-zen/plugins/organization";

export default defineSchema({
  ...coreSchemaTables,
  ...(systemAdminPluginFactory.definition.schema?.tables ?? {}),
  ...(organizationPluginFactory.definition.schema?.tables ?? {}),
});
