// @generated by convex-zen generate. DO NOT EDIT.
export const authMeta = {
  "core": {
    "currentUser": "query",
    "getOAuthUrl": "mutation",
    "getUserById": "query",
    "handleOAuthCallback": "action",
    "invalidateAllSessions": "mutation",
    "invalidateSession": "mutation",
    "requestPasswordReset": "mutation",
    "resetPassword": "mutation",
    "signInWithEmail": "mutation",
    "signUp": "mutation",
    "validateSession": "mutation",
    "verifyEmail": "mutation"
  },
  "plugin": {
    "admin": {
      "banUser": "mutation",
      "deleteUser": "mutation",
      "isAdmin": "query",
      "listUsers": "query",
      "setRole": "mutation",
      "unbanUser": "mutation"
    },
    "organization": {
      "acceptIncomingInvitation": "mutation",
      "acceptInvitation": "mutation",
      "addDomain": "mutation",
      "cancelInvitation": "mutation",
      "checkSlug": "query",
      "createOrganization": "mutation",
      "createRole": "mutation",
      "declineIncomingInvitation": "mutation",
      "deleteOrganization": "mutation",
      "deleteRole": "mutation",
      "getDomainVerificationChallenge": "query",
      "getMembership": "query",
      "getOrganization": "query",
      "getRole": "query",
      "hasPermission": "query",
      "hasRole": "query",
      "inviteMember": "mutation",
      "listAvailablePermissions": "query",
      "listDomains": "query",
      "listIncomingInvitations": "query",
      "listInvitations": "query",
      "listMembers": "query",
      "listOrganizations": "query",
      "listRoles": "query",
      "markDomainVerified": "mutation",
      "removeDomain": "mutation",
      "removeMember": "mutation",
      "requirePermission": "query",
      "requireRole": "query",
      "resolveOrganizationByHost": "query",
      "setMemberRole": "mutation",
      "transferOwnership": "mutation",
      "updateOrganization": "mutation",
      "updateRole": "mutation"
    }
  }
} as const;

export const authCoreMeta = authMeta.core;
export const authPluginMeta = authMeta.plugin;

export type AuthMeta = typeof authMeta;
export type AuthCoreMeta = typeof authCoreMeta;
export type AuthPluginMeta = typeof authPluginMeta;
