// @generated by convex-zen generate. DO NOT EDIT.
import { mutation, query } from "../../_generated/server";
import { getPublicPluginFunctionArgs } from "convex-zen/component";
import { examplePlugin as examplePluginFactory } from "convex-zen-example";
import { auth } from "../../_runtime";

const pluginGateway = examplePluginFactory.definition.gateway;

type PluginRuntime = (typeof auth.plugins)["example"];
type PluginRuntimeReturn<TFunctionName extends keyof PluginRuntime & string> =
  PluginRuntime[TFunctionName] extends (...args: never[]) => infer TReturn
    ? TReturn
    : never;

function runPluginRuntimeFunction<TFunctionName extends keyof PluginRuntime & string>(
  ctx: unknown,
  functionName: TFunctionName,
  args: Record<string, unknown>
): PluginRuntimeReturn<TFunctionName> {
  const pluginRuntime = auth.plugins["example"];
  if (!pluginRuntime || typeof pluginRuntime !== "object") {
    throw new Error("Missing generated plugin runtime for \"example\".");
  }
  const fn = pluginRuntime[functionName];
  if (typeof fn !== "function") {
    throw new Error(
      `Missing generated plugin runtime function for "example.${functionName}".`
    );
  }
  return (
    fn as (
      this: PluginRuntime,
      ctx: unknown,
      args: Record<string, unknown>
    ) => PluginRuntimeReturn<TFunctionName>
  ).call(pluginRuntime, ctx, args);
}


export const listLogs = query({
  args: getPublicPluginFunctionArgs(pluginGateway.listLogs, "listLogs"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "listLogs", args);
  },
});

export const log = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.log, "log"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "log", args);
  },
});
