import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { tmpdir } from "node:os";
import { afterEach, describe, expect, it } from "vitest";
import { generateAuthFunctions } from "../src/cli/generate";

const tempDirs: string[] = [];

async function createTempWorkspace(): Promise<string> {
  const cwd = await mkdtemp(path.join(tmpdir(), "convex-zen-generate-"));
  tempDirs.push(cwd);
  await mkdir(path.join(cwd, "convex"), { recursive: true });
  return cwd;
}

async function writeZenConvexFile(cwd: string, source: string): Promise<void> {
  await writeFile(path.join(cwd, "convex", "zenConvex.ts"), source, "utf8");
}

async function writeZenConfigFile(cwd: string, source: string): Promise<void> {
  await writeFile(path.join(cwd, "convex", "zen.config.ts"), source, "utf8");
}

afterEach(async () => {
  await Promise.all(
    tempDirs.splice(0).map(async (dir) => {
      await rm(dir, { recursive: true, force: true });
    })
  );
});

describe("generateAuthFunctions", () => {
  it("generates core, plugin admin wrapper, and plugin metadata from zenConvex.ts", async () => {
    const cwd = await createTempWorkspace();
    await writeZenConvexFile(
      cwd,
      `
import { ConvexZen } from "convex-zen";
import { adminPlugin } from "convex-zen/plugins/admin";

export const authOptions = {
  plugins: [adminPlugin()],
};

export const auth = new ConvexZen({} as Record<string, unknown>, authOptions);
`
    );

    const result = await generateAuthFunctions({
      cwd,
      check: false,
      verbose: false,
    });

    expect(result.created).toContain(path.join("convex", "auth", "core.ts"));
    expect(result.created).toContain(
      path.join("convex", "auth", "metaGenerated.ts")
    );
    expect(result.created).toContain(
      path.join("convex", "auth", "plugin", "admin.ts")
    );
    expect(result.created).toContain(
      path.join("convex", "auth", "plugin", "metaGenerated.ts")
    );

    const coreSource = await readFile(
      path.join(cwd, "convex", "auth", "core.ts"),
      "utf8"
    );
    expect(coreSource).toContain('import { auth } from "../zenConvex";');
    expect(coreSource).toContain("export const signInWithEmail = mutation({");
    expect(coreSource).toContain("export const invalidateSession = mutation({");
    expect(coreSource).toContain("export const currentUser = query({");
    expect(coreSource).not.toContain("export const signOut = mutation({");
    expect(coreSource).not.toContain("export const signInWithEmailCore = mutation({");

    const metaSource = await readFile(
      path.join(cwd, "convex", "auth", "metaGenerated.ts"),
      "utf8"
    );
    expect(metaSource).toContain('"core"');
    expect(metaSource).toContain('"plugin"');
    expect(metaSource).toContain('"currentUser": "query"');

    const pluginMetaSource = await readFile(
      path.join(cwd, "convex", "auth", "plugin", "metaGenerated.ts"),
      "utf8"
    );
    expect(pluginMetaSource).toContain('export { authPluginMeta }');
  });

  it("deletes generated admin plugin wrapper when admin plugin is disabled", async () => {
    const cwd = await createTempWorkspace();
    await writeZenConvexFile(
      cwd,
      `
import { ConvexZen } from "convex-zen";

export const authOptions = {
  plugins: [],
};

export const auth = new ConvexZen({} as Record<string, unknown>, authOptions);
`
    );
    await mkdir(path.join(cwd, "convex", "auth", "plugin"), { recursive: true });
    await writeFile(
      path.join(cwd, "convex", "auth", "plugin", "admin.ts"),
      `// @generated by convex-zen generate. DO NOT EDIT.\nexport const stale = true;\n`,
      "utf8"
    );

    const result = await generateAuthFunctions({
      cwd,
      check: false,
      verbose: false,
    });

    expect(result.deleted).toContain(
      path.join("convex", "auth", "plugin", "admin.ts")
    );

    const metaSource = await readFile(
      path.join(cwd, "convex", "auth", "metaGenerated.ts"),
      "utf8"
    );
    expect(metaSource).toContain('"plugin": {}');

    const pluginMetaSource = await readFile(
      path.join(cwd, "convex", "auth", "plugin", "metaGenerated.ts"),
      "utf8"
    );
    expect(pluginMetaSource).toContain('export { authPluginMeta }');
  });

  it("generates wrappers from zen.config.ts when present", async () => {
    const cwd = await createTempWorkspace();
    await writeZenConfigFile(
      cwd,
      `
import { ConvexZen } from "convex-zen";
import { adminPlugin } from "convex-zen/plugins/admin";

export const authOptions = {
  plugins: [adminPlugin()],
};

export const auth = new ConvexZen({} as Record<string, unknown>, authOptions);
`
    );

    const result = await generateAuthFunctions({
      cwd,
      check: false,
      verbose: false,
    });

    expect(result.created).toContain(path.join("convex", "auth", "core.ts"));
    const coreSource = await readFile(
      path.join(cwd, "convex", "auth", "core.ts"),
      "utf8"
    );
    expect(coreSource).toContain('import { auth } from "../zen.config";');
  });

  it("generates oauth wrappers when providers use the generic provider array", async () => {
    const cwd = await createTempWorkspace();
    await writeZenConfigFile(
      cwd,
      `
import { ConvexZen, defineOAuthProvider } from "convex-zen";

const acmeProvider = defineOAuthProvider({
  id: "acme",
  createConfig: (config: { clientId: string; clientSecret: string }) => ({
    id: "acme",
    clientId: config.clientId,
    clientSecret: config.clientSecret,
    authorizationUrl: "https://acme.example/oauth/authorize",
    tokenUrl: "https://acme.example/oauth/token",
    userInfoUrl: "https://acme.example/api/me",
    scopes: ["profile", "email"],
  }),
  runtime: {
    buildAuthorizationUrl: () => "https://acme.example/oauth/authorize",
    exchangeAuthorizationCode: async () => ({ accessToken: "token" }),
    fetchProfile: async () => ({
      accountId: "acme-user",
      email: "acme@example.com",
      emailVerified: true,
    }),
  },
});

export const authOptions = {
  providers: [
    acmeProvider({
      clientId: "client-id",
      clientSecret: "client-secret",
    }),
  ],
};

export const auth = new ConvexZen({} as Record<string, unknown>, authOptions);
`
    );

    const result = await generateAuthFunctions({
      cwd,
      check: false,
      verbose: false,
    });

    expect(result.created).toContain(path.join("convex", "auth", "core.ts"));

    const coreSource = await readFile(
      path.join(cwd, "convex", "auth", "core.ts"),
      "utf8"
    );
    expect(coreSource).toContain("export const getOAuthUrl = mutation({");
    expect(coreSource).toContain("return auth.getOAuthUrl(ctx, args.providerId, {");
    expect(coreSource).toContain("return auth.handleCallback(ctx, args);");
  });
});
