import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { tmpdir } from "node:os";
import { afterEach, describe, expect, it } from "vitest";
import { generateAuthFunctions } from "../src/cli/generate";

const tempDirs: string[] = [];

async function createTempWorkspace(): Promise<string> {
  const cwd = await mkdtemp(path.join(tmpdir(), "convex-zen-generate-"));
  tempDirs.push(cwd);
  await mkdir(path.join(cwd, "convex"), { recursive: true });
  return cwd;
}

async function writeZenConvexFile(cwd: string, source: string): Promise<void> {
  await writeFile(path.join(cwd, "convex", "zenConvex.ts"), source, "utf8");
}

afterEach(async () => {
  await Promise.all(
    tempDirs.splice(0).map(async (dir) => {
      await rm(dir, { recursive: true, force: true });
    })
  );
});

describe("generateAuthFunctions", () => {
  it("generates core, plugin admin wrapper, and plugin metadata from zenConvex.ts", async () => {
    const cwd = await createTempWorkspace();
    await writeZenConvexFile(
      cwd,
      `
import { ConvexZen } from "convex-zen";
import { adminPlugin } from "convex-zen/plugins/admin";

export const authOptions = {
  plugins: [adminPlugin()],
};

export const auth = new ConvexZen({} as Record<string, unknown>, authOptions);
`
    );

    const result = await generateAuthFunctions({
      cwd,
      check: false,
      verbose: false,
    });

    expect(result.created).toContain(path.join("convex", "auth", "core.ts"));
    expect(result.created).toContain(
      path.join("convex", "auth", "plugin", "admin.ts")
    );
    expect(result.created).toContain(
      path.join("convex", "auth", "plugin", "metaGenerated.ts")
    );

    const coreSource = await readFile(
      path.join(cwd, "convex", "auth", "core.ts"),
      "utf8"
    );
    expect(coreSource).toContain('import { auth } from "../zenConvex";');

    const metaSource = await readFile(
      path.join(cwd, "convex", "auth", "plugin", "metaGenerated.ts"),
      "utf8"
    );
    expect(metaSource).toContain('"admin"');
    expect(metaSource).toContain('"listUsers": "query"');
  });

  it("deletes generated admin plugin wrapper when admin plugin is disabled", async () => {
    const cwd = await createTempWorkspace();
    await writeZenConvexFile(
      cwd,
      `
import { ConvexZen } from "convex-zen";

export const authOptions = {
  plugins: [],
};

export const auth = new ConvexZen({} as Record<string, unknown>, authOptions);
`
    );
    await mkdir(path.join(cwd, "convex", "auth", "plugin"), { recursive: true });
    await writeFile(
      path.join(cwd, "convex", "auth", "plugin", "admin.ts"),
      `// @generated by convex-zen generate. DO NOT EDIT.\nexport const stale = true;\n`,
      "utf8"
    );

    const result = await generateAuthFunctions({
      cwd,
      check: false,
      verbose: false,
    });

    expect(result.deleted).toContain(
      path.join("convex", "auth", "plugin", "admin.ts")
    );

    const metaSource = await readFile(
      path.join(cwd, "convex", "auth", "plugin", "metaGenerated.ts"),
      "utf8"
    );
    expect(metaSource).not.toContain('"admin"');
  });
});
