// @generated by convex-zen generate. DO NOT EDIT.
import { v } from "convex/values";
import { mutation, query } from "../../_generated/server";
import { auth } from "../../zen.config";

async function requireActorUserId(ctx: { auth: { getUserIdentity: () => Promise<{ subject?: string } | null> } }): Promise<string> {
  const identity = await ctx.auth.getUserIdentity();
  const actorUserId = identity?.subject;
  if (!actorUserId) {
    throw new Error("Unauthorized: missing identity subject");
  }
  return actorUserId;
}

export const isAdmin = query({
  args: {},
  handler: async (ctx) => {
    if (!auth.plugins.admin) {
      throw new Error("Admin plugin is not enabled");
    }
    const identity = await ctx.auth.getUserIdentity();
    const actorUserId = identity?.subject;
    if (!actorUserId) {
      return false;
    }
    return auth.plugins.admin.isAdmin(ctx, { actorUserId });
  },
});

export const listUsers = query({
  args: {
    limit: v.optional(v.number()),
    cursor: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    if (!auth.plugins.admin) {
      throw new Error("Admin plugin is not enabled");
    }
    const actorUserId = await requireActorUserId(ctx);
    return auth.plugins.admin.listUsers(ctx, { actorUserId, ...args });
  },
});

export const banUser = mutation({
  args: {
    userId: v.string(),
    reason: v.optional(v.string()),
    expiresAt: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    if (!auth.plugins.admin) {
      throw new Error("Admin plugin is not enabled");
    }
    const actorUserId = await requireActorUserId(ctx);
    return auth.plugins.admin.banUser(ctx, { actorUserId, ...args });
  },
});

export const unbanUser = mutation({
  args: {
    userId: v.string(),
  },
  handler: async (ctx, args) => {
    if (!auth.plugins.admin) {
      throw new Error("Admin plugin is not enabled");
    }
    const actorUserId = await requireActorUserId(ctx);
    return auth.plugins.admin.unbanUser(ctx, { actorUserId, ...args });
  },
});

export const setRole = mutation({
  args: {
    userId: v.string(),
    role: v.string(),
  },
  handler: async (ctx, args) => {
    if (!auth.plugins.admin) {
      throw new Error("Admin plugin is not enabled");
    }
    const actorUserId = await requireActorUserId(ctx);
    return auth.plugins.admin.setRole(ctx, { actorUserId, ...args });
  },
});

export const deleteUser = mutation({
  args: {
    userId: v.string(),
  },
  handler: async (ctx, args) => {
    if (!auth.plugins.admin) {
      throw new Error("Admin plugin is not enabled");
    }
    const actorUserId = await requireActorUserId(ctx);
    return auth.plugins.admin.deleteUser(ctx, { actorUserId, ...args });
  },
});
