// @generated by convex-zen generate. DO NOT EDIT.
import { v } from "convex/values";
import { mutation, query } from "../../_generated/server";
import { auth } from "../../zen.config";

const organizationPermissionValidator = v.object({
  resource: v.string(),
  action: v.string(),
});

const organizationRoleAssignmentValidator = v.union(
  v.object({
    type: v.literal("system"),
    systemRole: v.string(),
  }),
  v.object({
    type: v.literal("custom"),
    customRoleId: v.string(),
  }),
);

type OrganizationApi = NonNullable<typeof auth.organization>;
type InviteMemberArgs = Parameters<OrganizationApi["inviteMember"]>[1];
type SetMemberRoleArgs = Parameters<OrganizationApi["setMemberRole"]>[1];
type HasRoleArgs = Parameters<OrganizationApi["hasRole"]>[1];
type RequireRoleArgs = Parameters<OrganizationApi["requireRole"]>[1];
type HasPermissionArgs = Parameters<OrganizationApi["hasPermission"]>[1];
type RequirePermissionArgs = Parameters<OrganizationApi["requirePermission"]>[1];

export const checkSlug = query({
  args: {
    slug: v.string(),
  },
  handler: async (ctx, args) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.checkSlug(ctx, args);
  },
});

export const createOrganization = mutation({
  args: {
    name: v.string(),
    slug: v.string(),
    logo: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.createOrganization(ctx, args);
  },
});

export const updateOrganization = mutation({
  args: {
    organizationId: v.string(),
    name: v.optional(v.string()),
    slug: v.optional(v.string()),
    logo: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.updateOrganization(ctx, args);
  },
});

export const deleteOrganization = mutation({
  args: {
    organizationId: v.string(),
  },
  handler: async (ctx, args) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.deleteOrganization(ctx, args);
  },
});

export const listOrganizations = query({
  args: {},
  handler: async (ctx) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.listOrganizations(ctx);
  },
});

export const getOrganization = query({
  args: {
    organizationId: v.string(),
  },
  handler: async (ctx, args) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.getOrganization(ctx, args);
  },
});

export const getMembership = query({
  args: {
    organizationId: v.string(),
  },
  handler: async (ctx, args) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.getMembership(ctx, args);
  },
});

export const listMembers = query({
  args: {
    organizationId: v.string(),
  },
  handler: async (ctx, args) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.listMembers(ctx, args);
  },
});

export const inviteMember = mutation({
  args: {
    organizationId: v.string(),
    email: v.string(),
    role: organizationRoleAssignmentValidator,
  },
  handler: async (ctx, args) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.inviteMember(ctx, args as InviteMemberArgs);
  },
});

export const listInvitations = query({
  args: {
    organizationId: v.string(),
  },
  handler: async (ctx, args) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.listInvitations(ctx, args);
  },
});

export const listIncomingInvitations = query({
  args: {},
  handler: async (ctx) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.listIncomingInvitations(ctx);
  },
});

export const acceptInvitation = mutation({
  args: {
    token: v.string(),
  },
  handler: async (ctx, args) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.acceptInvitation(ctx, args);
  },
});

export const acceptIncomingInvitation = mutation({
  args: {
    invitationId: v.string(),
  },
  handler: async (ctx, args) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.acceptIncomingInvitation(ctx, args);
  },
});

export const cancelInvitation = mutation({
  args: {
    invitationId: v.string(),
  },
  handler: async (ctx, args) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.cancelInvitation(ctx, args);
  },
});

export const declineIncomingInvitation = mutation({
  args: {
    invitationId: v.string(),
  },
  handler: async (ctx, args) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.declineIncomingInvitation(ctx, args);
  },
});

export const removeMember = mutation({
  args: {
    organizationId: v.string(),
    userId: v.string(),
  },
  handler: async (ctx, args) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.removeMember(ctx, args);
  },
});

export const setMemberRole = mutation({
  args: {
    organizationId: v.string(),
    userId: v.string(),
    role: organizationRoleAssignmentValidator,
  },
  handler: async (ctx, args) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.setMemberRole(ctx, args as SetMemberRoleArgs);
  },
});

export const transferOwnership = mutation({
  args: {
    organizationId: v.string(),
    newOwnerUserId: v.string(),
  },
  handler: async (ctx, args) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.transferOwnership(ctx, args);
  },
});

export const createRole = mutation({
  args: {
    organizationId: v.string(),
    name: v.string(),
    slug: v.string(),
    description: v.optional(v.string()),
    permissions: v.array(v.string()),
  },
  handler: async (ctx, args) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.createRole(ctx, args);
  },
});

export const listRoles = query({
  args: {
    organizationId: v.string(),
  },
  handler: async (ctx, args) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.listRoles(ctx, args);
  },
});

export const listAvailablePermissions = query({
  args: {
    organizationId: v.string(),
  },
  handler: async (ctx, args) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.listAvailablePermissions(ctx, args);
  },
});

export const getRole = query({
  args: {
    roleId: v.string(),
  },
  handler: async (ctx, args) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.getRole(ctx, args);
  },
});

export const updateRole = mutation({
  args: {
    roleId: v.string(),
    name: v.optional(v.string()),
    slug: v.optional(v.string()),
    description: v.optional(v.string()),
    permissions: v.optional(v.array(v.string())),
  },
  handler: async (ctx, args) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.updateRole(ctx, args);
  },
});

export const deleteRole = mutation({
  args: {
    roleId: v.string(),
  },
  handler: async (ctx, args) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.deleteRole(ctx, args);
  },
});

export const addDomain = mutation({
  args: {
    organizationId: v.string(),
    hostname: v.string(),
  },
  handler: async (ctx, args) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.addDomain(ctx, args);
  },
});

export const listDomains = query({
  args: {
    organizationId: v.string(),
  },
  handler: async (ctx, args) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.listDomains(ctx, args);
  },
});

export const getDomainVerificationChallenge = query({
  args: {
    domainId: v.string(),
  },
  handler: async (ctx, args) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.getDomainVerificationChallenge(ctx, args);
  },
});

export const markDomainVerified = mutation({
  args: {
    domainId: v.string(),
  },
  handler: async (ctx, args) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.markDomainVerified(ctx, args);
  },
});

export const removeDomain = mutation({
  args: {
    domainId: v.string(),
  },
  handler: async (ctx, args) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.removeDomain(ctx, args);
  },
});

export const resolveOrganizationByHost = query({
  args: {
    host: v.string(),
  },
  handler: async (ctx, args) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.resolveOrganizationByHost(ctx, args);
  },
});

export const hasRole = query({
  args: {
    organizationId: v.string(),
    role: v.optional(v.string()),
    roles: v.optional(v.array(v.string())),
  },
  handler: async (ctx, args) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.hasRole(ctx, args as HasRoleArgs);
  },
});

export const requireRole = query({
  args: {
    organizationId: v.string(),
    role: v.optional(v.string()),
    roles: v.optional(v.array(v.string())),
  },
  handler: async (ctx, args) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.requireRole(ctx, args as RequireRoleArgs);
  },
});

export const hasPermission = query({
  args: {
    organizationId: v.string(),
    permission: organizationPermissionValidator,
  },
  handler: async (ctx, args) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.hasPermission(ctx, args as HasPermissionArgs);
  },
});

export const requirePermission = query({
  args: {
    organizationId: v.string(),
    permission: organizationPermissionValidator,
  },
  handler: async (ctx, args) => {
    if (!auth.organization) {
      throw new Error("Organization plugin is not enabled");
    }
    return auth.organization.requirePermission(ctx, args as RequirePermissionArgs);
  },
});
