// @generated by convex-zen generate. DO NOT EDIT.
import { v } from "convex/values";
import { mutation, query } from "../../_generated/server";
import { auth } from "../generated";

async function requireActorUserId(ctx: { auth: { getUserIdentity: () => Promise<{ subject?: string } | null> } }): Promise<string> {
  const identity = await ctx.auth.getUserIdentity();
  const actorUserId = identity?.subject;
  if (!actorUserId) {
    throw new Error("Unauthorized: missing identity subject");
  }
  return actorUserId;
}

const organizationPermissionValidator = v.object({
  resource: v.string(),
  action: v.string(),
});

const organizationRoleAssignmentValidator = v.union(
  v.object({
    type: v.literal("system"),
    systemRole: v.string(),
  }),
  v.object({
    type: v.literal("custom"),
    customRoleId: v.string(),
  }),
);

export const checkSlug = query({
  args: {
    slug: v.string(),
  },
  handler: async (ctx, args) => {
    return auth.plugins.organization.checkSlug(ctx, args as any);
  },
});

export const createOrganization = mutation({
  args: {
    actorUserId: v.optional(v.string()),
    name: v.string(),
    slug: v.string(),
    logo: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.organization.createOrganization(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const updateOrganization = mutation({
  args: {
    actorUserId: v.optional(v.string()),
    organizationId: v.string(),
    name: v.optional(v.string()),
    slug: v.optional(v.string()),
    logo: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.organization.updateOrganization(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const deleteOrganization = mutation({
  args: {
    actorUserId: v.optional(v.string()),
    organizationId: v.string(),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.organization.deleteOrganization(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const listOrganizations = query({
  args: {
    actorUserId: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.organization.listOrganizations(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const getOrganization = query({
  args: {
    actorUserId: v.optional(v.string()),
    organizationId: v.string(),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.organization.getOrganization(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const getMembership = query({
  args: {
    actorUserId: v.optional(v.string()),
    organizationId: v.string(),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.organization.getMembership(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const listMembers = query({
  args: {
    actorUserId: v.optional(v.string()),
    organizationId: v.string(),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.organization.listMembers(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const inviteMember = mutation({
  args: {
    actorUserId: v.optional(v.string()),
    organizationId: v.string(),
    email: v.string(),
    role: organizationRoleAssignmentValidator,
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.organization.inviteMember(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const listInvitations = query({
  args: {
    actorUserId: v.optional(v.string()),
    organizationId: v.string(),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.organization.listInvitations(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const listIncomingInvitations = query({
  args: {
    actorUserId: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.organization.listIncomingInvitations(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const acceptInvitation = mutation({
  args: {
    actorUserId: v.optional(v.string()),
    token: v.string(),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.organization.acceptInvitation(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const acceptIncomingInvitation = mutation({
  args: {
    actorUserId: v.optional(v.string()),
    invitationId: v.string(),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.organization.acceptIncomingInvitation(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const cancelInvitation = mutation({
  args: {
    actorUserId: v.optional(v.string()),
    invitationId: v.string(),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.organization.cancelInvitation(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const declineIncomingInvitation = mutation({
  args: {
    actorUserId: v.optional(v.string()),
    invitationId: v.string(),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.organization.declineIncomingInvitation(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const removeMember = mutation({
  args: {
    actorUserId: v.optional(v.string()),
    organizationId: v.string(),
    userId: v.string(),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.organization.removeMember(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const setMemberRole = mutation({
  args: {
    actorUserId: v.optional(v.string()),
    organizationId: v.string(),
    userId: v.string(),
    role: organizationRoleAssignmentValidator,
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.organization.setMemberRole(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const transferOwnership = mutation({
  args: {
    actorUserId: v.optional(v.string()),
    organizationId: v.string(),
    newOwnerUserId: v.string(),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.organization.transferOwnership(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const createRole = mutation({
  args: {
    actorUserId: v.optional(v.string()),
    organizationId: v.string(),
    name: v.string(),
    slug: v.string(),
    description: v.optional(v.string()),
    permissions: v.array(v.string()),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.organization.createRole(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const listRoles = query({
  args: {
    actorUserId: v.optional(v.string()),
    organizationId: v.string(),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.organization.listRoles(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const listAvailablePermissions = query({
  args: {
    actorUserId: v.optional(v.string()),
    organizationId: v.string(),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.organization.listAvailablePermissions(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const getRole = query({
  args: {
    actorUserId: v.optional(v.string()),
    roleId: v.string(),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.organization.getRole(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const updateRole = mutation({
  args: {
    actorUserId: v.optional(v.string()),
    roleId: v.string(),
    name: v.optional(v.string()),
    slug: v.optional(v.string()),
    description: v.optional(v.string()),
    permissions: v.optional(v.array(v.string())),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.organization.updateRole(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const deleteRole = mutation({
  args: {
    actorUserId: v.optional(v.string()),
    roleId: v.string(),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.organization.deleteRole(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const addDomain = mutation({
  args: {
    actorUserId: v.optional(v.string()),
    organizationId: v.string(),
    hostname: v.string(),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.organization.addDomain(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const listDomains = query({
  args: {
    actorUserId: v.optional(v.string()),
    organizationId: v.string(),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.organization.listDomains(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const getDomainVerificationChallenge = query({
  args: {
    actorUserId: v.optional(v.string()),
    domainId: v.string(),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.organization.getDomainVerificationChallenge(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const markDomainVerified = mutation({
  args: {
    actorUserId: v.optional(v.string()),
    domainId: v.string(),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.organization.markDomainVerified(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const removeDomain = mutation({
  args: {
    actorUserId: v.optional(v.string()),
    domainId: v.string(),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.organization.removeDomain(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const resolveOrganizationByHost = query({
  args: {
    host: v.string(),
  },
  handler: async (ctx, args) => {
    return auth.plugins.organization.resolveOrganizationByHost(ctx, args as any);
  },
});

export const hasRole = query({
  args: {
    actorUserId: v.optional(v.string()),
    organizationId: v.string(),
    role: v.optional(v.string()),
    roles: v.optional(v.array(v.string())),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.organization.hasRole(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const requireRole = query({
  args: {
    actorUserId: v.optional(v.string()),
    organizationId: v.string(),
    role: v.optional(v.string()),
    roles: v.optional(v.array(v.string())),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.organization.requireRole(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const hasPermission = query({
  args: {
    actorUserId: v.optional(v.string()),
    organizationId: v.string(),
    permission: organizationPermissionValidator,
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.organization.hasPermission(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const requirePermission = query({
  args: {
    actorUserId: v.optional(v.string()),
    organizationId: v.string(),
    permission: organizationPermissionValidator,
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.organization.requirePermission(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});
