// @generated by convex-zen generate. DO NOT EDIT.
import { v } from "convex/values";
import { action } from "../_generated/server";
import { auth } from "./index";

export const listUsers = action({
  args: {
    token: v.optional(v.string()),
    limit: v.optional(v.number()),
    cursor: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    if (!auth.admin) {
      throw new Error("Admin plugin is not enabled");
    }
    return auth.admin.listUsers(ctx, args);
  },
});

export const banUser = action({
  args: {
    token: v.optional(v.string()),
    userId: v.string(),
    reason: v.optional(v.string()),
    expiresAt: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    if (!auth.admin) {
      throw new Error("Admin plugin is not enabled");
    }
    return auth.admin.banUser(ctx, args);
  },
});

export const unbanUser = action({
  args: {
    token: v.optional(v.string()),
    userId: v.string(),
  },
  handler: async (ctx, args) => {
    if (!auth.admin) {
      throw new Error("Admin plugin is not enabled");
    }
    return auth.admin.unbanUser(ctx, args);
  },
});

export const setRole = action({
  args: {
    token: v.optional(v.string()),
    userId: v.string(),
    role: v.string(),
  },
  handler: async (ctx, args) => {
    if (!auth.admin) {
      throw new Error("Admin plugin is not enabled");
    }
    return auth.admin.setRole(ctx, args);
  },
});

export const deleteUser = action({
  args: {
    token: v.optional(v.string()),
    userId: v.string(),
  },
  handler: async (ctx, args) => {
    if (!auth.admin) {
      throw new Error("Admin plugin is not enabled");
    }
    return auth.admin.deleteUser(ctx, args);
  },
});
