// @generated by convex-zen generate. DO NOT EDIT.
import { v } from "convex/values";
import { mutation } from "../_generated/server";
import { auth } from "../zenConvex";

export const signUp = mutation({
	args: {
		email: v.string(),
		password: v.string(),
		name: v.optional(v.string()),
		ipAddress: v.optional(v.string()),
	},
	handler: async (ctx, args) => {
		return auth.signUp(ctx, args);
	},
});

export const signInWithEmail = mutation({
	args: {
		email: v.string(),
		password: v.string(),
		ipAddress: v.optional(v.string()),
		userAgent: v.optional(v.string()),
	},
	handler: async (ctx, args) => {
		return auth.signIn(ctx, args);
	},
});

export const verifyEmail = mutation({
	args: {
		email: v.string(),
		code: v.string(),
	},
	handler: async (ctx, args) => {
		return auth.verifyEmail(ctx, args);
	},
});

export const requestPasswordReset = mutation({
	args: {
		email: v.string(),
		ipAddress: v.optional(v.string()),
	},
	handler: async (ctx, args) => {
		return auth.requestPasswordReset(ctx, args);
	},
});

export const resetPassword = mutation({
	args: {
		email: v.string(),
		code: v.string(),
		newPassword: v.string(),
	},
	handler: async (ctx, args) => {
		return auth.resetPassword(ctx, args);
	},
});

export const signOut = mutation({
	args: {
		token: v.string(),
	},
	handler: async (ctx, args) => {
		await auth.signOut(ctx, args.token);
	},
});

export const validateSession = mutation({
	args: {
		token: v.string(),
	},
	handler: async (ctx, args) => {
		return auth.session.validate(ctx, args.token);
	},
});

export const currentUser = mutation({
	args: {
		token: v.optional(v.string()),
	},
	handler: async (ctx, args) => {
		return auth.user.safeGet(ctx, args.token);
	},
});
