// @generated by convex-zen generate. DO NOT EDIT.
import { v } from "convex/values";
import { action } from "../_generated/server";
import { auth } from "./index";

export const signUp = action({
  args: {
    email: v.string(),
    password: v.string(),
    name: v.optional(v.string()),
    ipAddress: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return auth.signUp(ctx, args);
  },
});

export const signInWithEmail = action({
  args: {
    email: v.string(),
    password: v.string(),
    ipAddress: v.optional(v.string()),
    userAgent: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return auth.signIn(ctx, args);
  },
});

export const verifyEmail = action({
  args: {
    email: v.string(),
    code: v.string(),
  },
  handler: async (ctx, args) => {
    return auth.verifyEmail(ctx, args);
  },
});

export const requestPasswordReset = action({
  args: {
    email: v.string(),
    ipAddress: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return auth.requestPasswordReset(ctx, args);
  },
});

export const resetPassword = action({
  args: {
    email: v.string(),
    code: v.string(),
    newPassword: v.string(),
  },
  handler: async (ctx, args) => {
    return auth.resetPassword(ctx, args);
  },
});

export const signOut = action({
  args: {
    token: v.string(),
  },
  handler: async (ctx, args) => {
    await auth.signOut(ctx, args.token);
  },
});

export const validateSession = action({
  args: {
    token: v.string(),
  },
  handler: async (ctx, args) => {
    return auth.session.validate(ctx, args.token);
  },
});

export const currentUser = action({
  args: {
    token: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return auth.user.safeGet(ctx, args.token);
  },
});

export const getOAuthUrl = action({
  args: {
    providerId: v.string(),
    redirectUrl: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return auth.getOAuthUrl(ctx, args.providerId, args.redirectUrl);
  },
});

export const handleOAuthCallback = action({
  args: {
    providerId: v.string(),
    code: v.string(),
    state: v.string(),
    redirectUrl: v.optional(v.string()),
    ipAddress: v.optional(v.string()),
    userAgent: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    return auth.handleCallback(ctx, args);
  },
});
