// @generated by convex-zen generate. DO NOT EDIT.
import { mutation, query } from "../../_generated/server";
import { getPublicPluginFunctionArgs } from "convex-zen/component";
import * as pluginGateway from "convex-zen-organization/gateway";
import { auth } from "../_generated/auth";

export const acceptIncomingInvitation = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.acceptIncomingInvitation, "acceptIncomingInvitation"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.acceptIncomingInvitation(ctx, args);
  },
});

export const acceptInvitation = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.acceptInvitation, "acceptInvitation"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.acceptInvitation(ctx, args);
  },
});

export const addDomain = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.addDomain, "addDomain"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.addDomain(ctx, args);
  },
});

export const cancelInvitation = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.cancelInvitation, "cancelInvitation"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.cancelInvitation(ctx, args);
  },
});

export const checkSlug = query({
  args: getPublicPluginFunctionArgs(pluginGateway.checkSlug, "checkSlug"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.checkSlug(ctx, args);
  },
});

export const createOrganization = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.createOrganization, "createOrganization"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.createOrganization(ctx, args);
  },
});

export const createRole = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.createRole, "createRole"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.createRole(ctx, args);
  },
});

export const declineIncomingInvitation = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.declineIncomingInvitation, "declineIncomingInvitation"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.declineIncomingInvitation(ctx, args);
  },
});

export const deleteOrganization = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.deleteOrganization, "deleteOrganization"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.deleteOrganization(ctx, args);
  },
});

export const deleteRole = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.deleteRole, "deleteRole"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.deleteRole(ctx, args);
  },
});

export const getDomainVerificationChallenge = query({
  args: getPublicPluginFunctionArgs(pluginGateway.getDomainVerificationChallenge, "getDomainVerificationChallenge"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.getDomainVerificationChallenge(ctx, args);
  },
});

export const getMembership = query({
  args: getPublicPluginFunctionArgs(pluginGateway.getMembership, "getMembership"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.getMembership(ctx, args);
  },
});

export const getOrganization = query({
  args: getPublicPluginFunctionArgs(pluginGateway.getOrganization, "getOrganization"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.getOrganization(ctx, args);
  },
});

export const getRole = query({
  args: getPublicPluginFunctionArgs(pluginGateway.getRole, "getRole"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.getRole(ctx, args);
  },
});

export const hasPermission = query({
  args: getPublicPluginFunctionArgs(pluginGateway.hasPermission, "hasPermission"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.hasPermission(ctx, args);
  },
});

export const hasRole = query({
  args: getPublicPluginFunctionArgs(pluginGateway.hasRole, "hasRole"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.hasRole(ctx, args);
  },
});

export const inviteMember = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.inviteMember, "inviteMember"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.inviteMember(ctx, args);
  },
});

export const listAvailablePermissions = query({
  args: getPublicPluginFunctionArgs(pluginGateway.listAvailablePermissions, "listAvailablePermissions"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.listAvailablePermissions(ctx, args);
  },
});

export const listDomains = query({
  args: getPublicPluginFunctionArgs(pluginGateway.listDomains, "listDomains"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.listDomains(ctx, args);
  },
});

export const listIncomingInvitations = query({
  args: getPublicPluginFunctionArgs(pluginGateway.listIncomingInvitations, "listIncomingInvitations"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.listIncomingInvitations(ctx, args);
  },
});

export const listInvitations = query({
  args: getPublicPluginFunctionArgs(pluginGateway.listInvitations, "listInvitations"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.listInvitations(ctx, args);
  },
});

export const listMembers = query({
  args: getPublicPluginFunctionArgs(pluginGateway.listMembers, "listMembers"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.listMembers(ctx, args);
  },
});

export const listOrganizations = query({
  args: getPublicPluginFunctionArgs(pluginGateway.listOrganizations, "listOrganizations"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.listOrganizations(ctx, args);
  },
});

export const listRoles = query({
  args: getPublicPluginFunctionArgs(pluginGateway.listRoles, "listRoles"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.listRoles(ctx, args);
  },
});

export const markDomainVerified = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.markDomainVerified, "markDomainVerified"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.markDomainVerified(ctx, args);
  },
});

export const removeDomain = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.removeDomain, "removeDomain"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.removeDomain(ctx, args);
  },
});

export const removeMember = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.removeMember, "removeMember"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.removeMember(ctx, args);
  },
});

export const requirePermission = query({
  args: getPublicPluginFunctionArgs(pluginGateway.requirePermission, "requirePermission"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.requirePermission(ctx, args);
  },
});

export const requireRole = query({
  args: getPublicPluginFunctionArgs(pluginGateway.requireRole, "requireRole"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.requireRole(ctx, args);
  },
});

export const resolveOrganizationByHost = query({
  args: getPublicPluginFunctionArgs(pluginGateway.resolveOrganizationByHost, "resolveOrganizationByHost"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.resolveOrganizationByHost(ctx, args);
  },
});

export const setMemberRole = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.setMemberRole, "setMemberRole"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.setMemberRole(ctx, args);
  },
});

export const transferOwnership = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.transferOwnership, "transferOwnership"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.transferOwnership(ctx, args);
  },
});

export const updateOrganization = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.updateOrganization, "updateOrganization"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.updateOrganization(ctx, args);
  },
});

export const updateRole = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.updateRole, "updateRole"),
  handler: async (ctx, args) => {
    return auth.plugins.organization.updateRole(ctx, args);
  },
});
