// @generated by convex-zen generate. DO NOT EDIT.
import { mutation, query } from "../../_generated/server";
import { components } from "../../_generated/api";
import { getPublicPluginFunctionArgs } from "convex-zen/component";
import { organizationPlugin as organizationPluginFactory } from "convex-zen/plugins/organization";


const pluginGateway = organizationPluginFactory.definition.gateway;


export const acceptIncomingInvitation = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.acceptIncomingInvitation, "acceptIncomingInvitation"),
  handler: async (ctx, args) => {
    return ctx.runMutation(components.zenComponent.plugins.organization.gateway.acceptIncomingInvitation, args);
  },
});

export const acceptInvitation = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.acceptInvitation, "acceptInvitation"),
  handler: async (ctx, args) => {
    return ctx.runMutation(components.zenComponent.plugins.organization.gateway.acceptInvitation, args);
  },
});

export const addDomain = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.addDomain, "addDomain"),
  handler: async (ctx, args) => {
    return ctx.runMutation(components.zenComponent.plugins.organization.gateway.addDomain, args);
  },
});

export const cancelInvitation = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.cancelInvitation, "cancelInvitation"),
  handler: async (ctx, args) => {
    return ctx.runMutation(components.zenComponent.plugins.organization.gateway.cancelInvitation, args);
  },
});

export const checkSlug = query({
  args: getPublicPluginFunctionArgs(pluginGateway.checkSlug, "checkSlug"),
  handler: async (ctx, args) => {
    return ctx.runQuery(components.zenComponent.plugins.organization.gateway.checkSlug, args);
  },
});

export const createOrganization = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.createOrganization, "createOrganization"),
  handler: async (ctx, args) => {
    return ctx.runMutation(components.zenComponent.plugins.organization.gateway.createOrganization, args);
  },
});

export const createRole = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.createRole, "createRole"),
  handler: async (ctx, args) => {
    return ctx.runMutation(components.zenComponent.plugins.organization.gateway.createRole, args);
  },
});

export const declineIncomingInvitation = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.declineIncomingInvitation, "declineIncomingInvitation"),
  handler: async (ctx, args) => {
    return ctx.runMutation(components.zenComponent.plugins.organization.gateway.declineIncomingInvitation, args);
  },
});

export const deleteOrganization = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.deleteOrganization, "deleteOrganization"),
  handler: async (ctx, args) => {
    return ctx.runMutation(components.zenComponent.plugins.organization.gateway.deleteOrganization, args);
  },
});

export const deleteRole = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.deleteRole, "deleteRole"),
  handler: async (ctx, args) => {
    return ctx.runMutation(components.zenComponent.plugins.organization.gateway.deleteRole, args);
  },
});

export const getDomainVerificationChallenge = query({
  args: getPublicPluginFunctionArgs(pluginGateway.getDomainVerificationChallenge, "getDomainVerificationChallenge"),
  handler: async (ctx, args) => {
    return ctx.runQuery(components.zenComponent.plugins.organization.gateway.getDomainVerificationChallenge, args);
  },
});

export const getMembership = query({
  args: getPublicPluginFunctionArgs(pluginGateway.getMembership, "getMembership"),
  handler: async (ctx, args) => {
    return ctx.runQuery(components.zenComponent.plugins.organization.gateway.getMembership, args);
  },
});

export const getOrganization = query({
  args: getPublicPluginFunctionArgs(pluginGateway.getOrganization, "getOrganization"),
  handler: async (ctx, args) => {
    return ctx.runQuery(components.zenComponent.plugins.organization.gateway.getOrganization, args);
  },
});

export const getRole = query({
  args: getPublicPluginFunctionArgs(pluginGateway.getRole, "getRole"),
  handler: async (ctx, args) => {
    return ctx.runQuery(components.zenComponent.plugins.organization.gateway.getRole, args);
  },
});

export const hasPermission = query({
  args: getPublicPluginFunctionArgs(pluginGateway.hasPermission, "hasPermission"),
  handler: async (ctx, args) => {
    return ctx.runQuery(components.zenComponent.plugins.organization.gateway.hasPermission, args);
  },
});

export const hasRole = query({
  args: getPublicPluginFunctionArgs(pluginGateway.hasRole, "hasRole"),
  handler: async (ctx, args) => {
    return ctx.runQuery(components.zenComponent.plugins.organization.gateway.hasRole, args);
  },
});

export const inviteMember = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.inviteMember, "inviteMember"),
  handler: async (ctx, args) => {
    return ctx.runMutation(components.zenComponent.plugins.organization.gateway.inviteMember, args);
  },
});

export const listAvailablePermissions = query({
  args: getPublicPluginFunctionArgs(pluginGateway.listAvailablePermissions, "listAvailablePermissions"),
  handler: async (ctx, args) => {
    return ctx.runQuery(components.zenComponent.plugins.organization.gateway.listAvailablePermissions, args);
  },
});

export const listDomains = query({
  args: getPublicPluginFunctionArgs(pluginGateway.listDomains, "listDomains"),
  handler: async (ctx, args) => {
    return ctx.runQuery(components.zenComponent.plugins.organization.gateway.listDomains, args);
  },
});

export const listIncomingInvitations = query({
  args: getPublicPluginFunctionArgs(pluginGateway.listIncomingInvitations, "listIncomingInvitations"),
  handler: async (ctx, args) => {
    return ctx.runQuery(components.zenComponent.plugins.organization.gateway.listIncomingInvitations, args);
  },
});

export const listInvitations = query({
  args: getPublicPluginFunctionArgs(pluginGateway.listInvitations, "listInvitations"),
  handler: async (ctx, args) => {
    return ctx.runQuery(components.zenComponent.plugins.organization.gateway.listInvitations, args);
  },
});

export const listMembers = query({
  args: getPublicPluginFunctionArgs(pluginGateway.listMembers, "listMembers"),
  handler: async (ctx, args) => {
    return ctx.runQuery(components.zenComponent.plugins.organization.gateway.listMembers, args);
  },
});

export const listOrganizations = query({
  args: getPublicPluginFunctionArgs(pluginGateway.listOrganizations, "listOrganizations"),
  handler: async (ctx, args) => {
    return ctx.runQuery(components.zenComponent.plugins.organization.gateway.listOrganizations, args);
  },
});

export const listRoles = query({
  args: getPublicPluginFunctionArgs(pluginGateway.listRoles, "listRoles"),
  handler: async (ctx, args) => {
    return ctx.runQuery(components.zenComponent.plugins.organization.gateway.listRoles, args);
  },
});

export const markDomainVerified = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.markDomainVerified, "markDomainVerified"),
  handler: async (ctx, args) => {
    return ctx.runMutation(components.zenComponent.plugins.organization.gateway.markDomainVerified, args);
  },
});

export const removeDomain = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.removeDomain, "removeDomain"),
  handler: async (ctx, args) => {
    return ctx.runMutation(components.zenComponent.plugins.organization.gateway.removeDomain, args);
  },
});

export const removeMember = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.removeMember, "removeMember"),
  handler: async (ctx, args) => {
    return ctx.runMutation(components.zenComponent.plugins.organization.gateway.removeMember, args);
  },
});

export const requirePermission = query({
  args: getPublicPluginFunctionArgs(pluginGateway.requirePermission, "requirePermission"),
  handler: async (ctx, args) => {
    return ctx.runQuery(components.zenComponent.plugins.organization.gateway.requirePermission, args);
  },
});

export const requireRole = query({
  args: getPublicPluginFunctionArgs(pluginGateway.requireRole, "requireRole"),
  handler: async (ctx, args) => {
    return ctx.runQuery(components.zenComponent.plugins.organization.gateway.requireRole, args);
  },
});

export const resolveOrganizationByHost = query({
  args: getPublicPluginFunctionArgs(pluginGateway.resolveOrganizationByHost, "resolveOrganizationByHost"),
  handler: async (ctx, args) => {
    return ctx.runQuery(components.zenComponent.plugins.organization.gateway.resolveOrganizationByHost, args);
  },
});

export const setMemberRole = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.setMemberRole, "setMemberRole"),
  handler: async (ctx, args) => {
    return ctx.runMutation(components.zenComponent.plugins.organization.gateway.setMemberRole, args);
  },
});

export const transferOwnership = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.transferOwnership, "transferOwnership"),
  handler: async (ctx, args) => {
    return ctx.runMutation(components.zenComponent.plugins.organization.gateway.transferOwnership, args);
  },
});

export const updateOrganization = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.updateOrganization, "updateOrganization"),
  handler: async (ctx, args) => {
    return ctx.runMutation(components.zenComponent.plugins.organization.gateway.updateOrganization, args);
  },
});

export const updateRole = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.updateRole, "updateRole"),
  handler: async (ctx, args) => {
    return ctx.runMutation(components.zenComponent.plugins.organization.gateway.updateRole, args);
  },
});
