// @generated by convex-zen generate. DO NOT EDIT.
import { components } from "./_generated/api";
import { createConvexZenClient } from "convex-zen";
import zenConfig from "../../zen.config";

const runtimeComponent = {
  core: components.core,
  "exampleComponent": components["exampleComponent"],
  "systemAdminComponent": components["systemAdminComponent"],
  "organizationComponent": components["organizationComponent"],
} as const;

export const auth = createConvexZenClient(
  runtimeComponent as Record<string, unknown>,
  zenConfig,
  { runtimeKind: "component" }
);
