// @generated by convex-zen generate. DO NOT EDIT.
import type { ApiFromModules } from "convex/server";
import * as core from "./core";
import * as plugin_admin from "./plugin/admin";
import * as plugin_organization from "./plugin/organization";


type AuthApi = ApiFromModules<{
  core: typeof core;
  "plugin/admin": typeof plugin_admin;
  "plugin/organization": typeof plugin_organization;
}>;

export const authConvexFunctions = {
  core: core as unknown as AuthApi["core"],
  plugin: {
    admin: plugin_admin as unknown as AuthApi["plugin"]["admin"],
    organization: plugin_organization as unknown as AuthApi["plugin"]["organization"],
  },
} as const;

export type AuthConvexFunctions = typeof authConvexFunctions;
