// @generated by convex-zen generate. DO NOT EDIT.
import { components } from "../_generated/api";
import { createConvexZenClient } from "convex-zen";
import { zenConfig } from "../zen.config";

export const auth = createConvexZenClient(
  components.zenComponent as Record<string, unknown>,
  zenConfig,
  { runtimeKind: "app" }
);

function resolveTokenEncryptionSecret(): string | undefined {
  const explicit = zenConfig.tokenEncryptionSecret?.trim();
  if (explicit && explicit.length > 0) {
    return explicit;
  }
  const envVar = zenConfig.tokenEncryptionSecretEnvVar ?? "CONVEX_ZEN_SECRET";
  const env = (globalThis as { process?: { env?: Record<string, string | undefined> } }).process?.env;
  const fromEnv = env?.[envVar]?.trim();
  return fromEnv && fromEnv.length > 0 ? fromEnv : undefined;
}

const oauthProviders = (zenConfig.providers ?? []).map((provider) => {
  if (provider.tokenEncryptionSecret !== undefined) {
    return provider;
  }
  const tokenEncryptionSecret = resolveTokenEncryptionSecret();
  if (!tokenEncryptionSecret) {
    return provider;
  }
  return {
    ...provider,
    tokenEncryptionSecret,
  };
});

export function resolveOAuthProvider(providerId: string) {
  return oauthProviders.find((provider) => provider.id === providerId);
}

export function resolveDefaultRole(): string | undefined {
  for (const plugin of zenConfig.plugins ?? []) {
    const role = plugin.definition.hooks?.onUserCreated?.defaultRole?.(
      plugin.options,
    );
    if (role !== undefined) {
      const trimmed = role.trim();
      return trimmed.length > 0 ? trimmed : undefined;
    }
  }
  return undefined;
}

export const authMeta = {
  "core": {
    "currentUser": "query",
    "getUserById": "query",
    "invalidateAllSessions": "mutation",
    "invalidateSession": "mutation",
    "requestPasswordReset": "mutation",
    "resetPassword": "mutation",
    "signInWithEmail": "mutation",
    "signUp": "mutation",
    "validateSession": "mutation",
    "verifyEmail": "mutation"
  },
  "plugin": {
    "admin": {
      "banUser": "mutation",
      "deleteUser": "mutation",
      "isAdmin": "query",
      "listUsers": "query",
      "setRole": "mutation",
      "unbanUser": "mutation"
    },
    "organization": {
      "acceptIncomingInvitation": "mutation",
      "acceptInvitation": "mutation",
      "addDomain": "mutation",
      "cancelInvitation": "mutation",
      "checkSlug": "query",
      "createOrganization": "mutation",
      "createRole": "mutation",
      "declineIncomingInvitation": "mutation",
      "deleteOrganization": "mutation",
      "deleteRole": "mutation",
      "getDomainVerificationChallenge": "query",
      "getMembership": "query",
      "getOrganization": "query",
      "getRole": "query",
      "hasPermission": "query",
      "hasRole": "query",
      "inviteMember": "mutation",
      "listAvailablePermissions": "query",
      "listDomains": "query",
      "listIncomingInvitations": "query",
      "listInvitations": "query",
      "listMembers": "query",
      "listOrganizations": "query",
      "listRoles": "query",
      "markDomainVerified": "mutation",
      "removeDomain": "mutation",
      "removeMember": "mutation",
      "requirePermission": "query",
      "requireRole": "query",
      "resolveOrganizationByHost": "query",
      "setMemberRole": "mutation",
      "transferOwnership": "mutation",
      "updateOrganization": "mutation",
      "updateRole": "mutation"
    }
  }
} as const;

export const authCoreMeta = authMeta.core;
export const authPluginMeta = authMeta.plugin;

export type AuthMeta = typeof authMeta;
export type AuthCoreMeta = typeof authCoreMeta;
export type AuthPluginMeta = typeof authPluginMeta;
