// @generated by convex-zen generate. DO NOT EDIT.
import { mutation, query } from "../../_generated/server";
import { getPublicPluginFunctionArgs } from "convex-zen/component";
import * as pluginGateway from "convex-zen-admin/gateway";
import { auth } from "../_generated/auth";

export const banUser = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.banUser, "banUser"),
  handler: async (ctx, args) => {
    return auth.plugins.admin.banUser(ctx, args);
  },
});

export const deleteUser = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.deleteUser, "deleteUser"),
  handler: async (ctx, args) => {
    return auth.plugins.admin.deleteUser(ctx, args);
  },
});

export const isAdmin = query({
  args: getPublicPluginFunctionArgs(pluginGateway.isAdmin, "isAdmin"),
  handler: async (ctx, args) => {
    return auth.plugins.admin.isAdmin(ctx, args);
  },
});

export const listUsers = query({
  args: getPublicPluginFunctionArgs(pluginGateway.listUsers, "listUsers"),
  handler: async (ctx, args) => {
    return auth.plugins.admin.listUsers(ctx, args);
  },
});

export const setRole = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.setRole, "setRole"),
  handler: async (ctx, args) => {
    return auth.plugins.admin.setRole(ctx, args);
  },
});

export const unbanUser = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.unbanUser, "unbanUser"),
  handler: async (ctx, args) => {
    return auth.plugins.admin.unbanUser(ctx, args);
  },
});
