// @generated by convex-zen generate. DO NOT EDIT.
import { mutation, query } from "../../_generated/server";
import { components } from "../../_generated/api";
import { getPublicPluginFunctionArgs } from "convex-zen/component";
import { examplePlugin as examplePluginFactory } from "convex-zen-example";


const pluginGateway = examplePluginFactory.definition.gateway;


export const listLogs = query({
  args: getPublicPluginFunctionArgs(pluginGateway.listLogs, "listLogs"),
  handler: async (ctx, args) => {
    return ctx.runQuery(components.zenComponent.plugins.example.gateway.listLogs, args);
  },
});

export const log = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.log, "log"),
  handler: async (ctx, args) => {
    return ctx.runMutation(components.zenComponent.plugins.example.gateway.log, args);
  },
});
