// @generated by convex-zen generate. DO NOT EDIT.
import { mutation, query } from "../../_generated/server";
import { getPublicPluginFunctionArgs } from "convex-zen/component";
import * as pluginGateway from "convex-zen-example/gateway";
import { auth } from "../_generated/auth";

export const listLogs = query({
  args: getPublicPluginFunctionArgs(pluginGateway.listLogs, "listLogs"),
  handler: async (ctx, args) => {
    return auth.plugins.example.listLogs(ctx, args);
  },
});

export const log = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.log, "log"),
  handler: async (ctx, args) => {
    return auth.plugins.example.log(ctx, args);
  },
});
