// @generated by convex-zen generate. DO NOT EDIT.
import { mutation, query } from "../../_generated/server";
import { components } from "../../_generated/api";
import { getPublicPluginFunctionArgs } from "convex-zen/component";
import { systemAdminPlugin as systemAdminPluginFactory } from "convex-zen/plugins/system-admin";


const pluginGateway = systemAdminPluginFactory.definition.gateway;


export const banUser = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.banUser, "banUser"),
  handler: async (ctx, args) => {
    return ctx.runMutation(components.zenComponent.plugins.systemAdmin.gateway.banUser, args);
  },
});

export const bootstrapAdmin = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.bootstrapAdmin, "bootstrapAdmin"),
  handler: async (ctx, args) => {
    return ctx.runMutation(components.zenComponent.plugins.systemAdmin.gateway.bootstrapAdmin, args);
  },
});

export const canBootstrapAdmin = query({
  args: getPublicPluginFunctionArgs(pluginGateway.canBootstrapAdmin, "canBootstrapAdmin"),
  handler: async (ctx, args) => {
    return ctx.runQuery(components.zenComponent.plugins.systemAdmin.gateway.canBootstrapAdmin, args);
  },
});

export const deleteUser = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.deleteUser, "deleteUser"),
  handler: async (ctx, args) => {
    return ctx.runMutation(components.zenComponent.plugins.systemAdmin.gateway.deleteUser, args);
  },
});

export const isAdmin = query({
  args: getPublicPluginFunctionArgs(pluginGateway.isAdmin, "isAdmin"),
  handler: async (ctx, args) => {
    return ctx.runQuery(components.zenComponent.plugins.systemAdmin.gateway.isAdmin, args);
  },
});

export const listUsers = query({
  args: getPublicPluginFunctionArgs(pluginGateway.listUsers, "listUsers"),
  handler: async (ctx, args) => {
    return ctx.runQuery(components.zenComponent.plugins.systemAdmin.gateway.listUsers, args);
  },
});

export const setRole = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.setRole, "setRole"),
  handler: async (ctx, args) => {
    return ctx.runMutation(components.zenComponent.plugins.systemAdmin.gateway.setRole, args);
  },
});

export const unbanUser = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.unbanUser, "unbanUser"),
  handler: async (ctx, args) => {
    return ctx.runMutation(components.zenComponent.plugins.systemAdmin.gateway.unbanUser, args);
  },
});
