// @generated by convex-zen generate. DO NOT EDIT.
import { mutation, query } from "../../_generated/server";
import { getPublicPluginFunctionArgs } from "convex-zen/component";
import { organizationPlugin as organizationPluginFactory } from "convex-zen/plugins/organization";
import { auth } from "../../_runtime";

const pluginGateway = organizationPluginFactory.definition.gateway;

type PluginRuntime = (typeof auth.plugins)["organization"];
type PluginRuntimeReturn<TFunctionName extends keyof PluginRuntime & string> =
  PluginRuntime[TFunctionName] extends (...args: never[]) => infer TReturn
    ? TReturn
    : never;

function runPluginRuntimeFunction<TFunctionName extends keyof PluginRuntime & string>(
  ctx: unknown,
  functionName: TFunctionName,
  args: Record<string, unknown>
): PluginRuntimeReturn<TFunctionName> {
  const pluginRuntime = auth.plugins["organization"];
  if (!pluginRuntime || typeof pluginRuntime !== "object") {
    throw new Error("Missing generated plugin runtime for \"organization\".");
  }
  const fn = pluginRuntime[functionName];
  if (typeof fn !== "function") {
    throw new Error(
      `Missing generated plugin runtime function for "organization.${functionName}".`
    );
  }
  return (
    fn as (
      this: PluginRuntime,
      ctx: unknown,
      args: Record<string, unknown>
    ) => PluginRuntimeReturn<TFunctionName>
  ).call(pluginRuntime, ctx, args);
}


export const acceptIncomingInvitation = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.acceptIncomingInvitation, "acceptIncomingInvitation"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "acceptIncomingInvitation", args);
  },
});

export const acceptInvitation = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.acceptInvitation, "acceptInvitation"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "acceptInvitation", args);
  },
});

export const addDomain = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.addDomain, "addDomain"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "addDomain", args);
  },
});

export const cancelInvitation = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.cancelInvitation, "cancelInvitation"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "cancelInvitation", args);
  },
});

export const checkSlug = query({
  args: getPublicPluginFunctionArgs(pluginGateway.checkSlug, "checkSlug"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "checkSlug", args);
  },
});

export const createOrganization = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.createOrganization, "createOrganization"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "createOrganization", args);
  },
});

export const createRole = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.createRole, "createRole"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "createRole", args);
  },
});

export const declineIncomingInvitation = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.declineIncomingInvitation, "declineIncomingInvitation"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "declineIncomingInvitation", args);
  },
});

export const deleteOrganization = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.deleteOrganization, "deleteOrganization"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "deleteOrganization", args);
  },
});

export const deleteRole = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.deleteRole, "deleteRole"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "deleteRole", args);
  },
});

export const getDomainVerificationChallenge = query({
  args: getPublicPluginFunctionArgs(pluginGateway.getDomainVerificationChallenge, "getDomainVerificationChallenge"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "getDomainVerificationChallenge", args);
  },
});

export const getMembership = query({
  args: getPublicPluginFunctionArgs(pluginGateway.getMembership, "getMembership"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "getMembership", args);
  },
});

export const getOrganization = query({
  args: getPublicPluginFunctionArgs(pluginGateway.getOrganization, "getOrganization"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "getOrganization", args);
  },
});

export const getRole = query({
  args: getPublicPluginFunctionArgs(pluginGateway.getRole, "getRole"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "getRole", args);
  },
});

export const hasPermission = query({
  args: getPublicPluginFunctionArgs(pluginGateway.hasPermission, "hasPermission"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "hasPermission", args);
  },
});

export const hasRole = query({
  args: getPublicPluginFunctionArgs(pluginGateway.hasRole, "hasRole"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "hasRole", args);
  },
});

export const inviteMember = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.inviteMember, "inviteMember"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "inviteMember", args);
  },
});

export const listAvailablePermissions = query({
  args: getPublicPluginFunctionArgs(pluginGateway.listAvailablePermissions, "listAvailablePermissions"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "listAvailablePermissions", args);
  },
});

export const listDomains = query({
  args: getPublicPluginFunctionArgs(pluginGateway.listDomains, "listDomains"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "listDomains", args);
  },
});

export const listIncomingInvitations = query({
  args: getPublicPluginFunctionArgs(pluginGateway.listIncomingInvitations, "listIncomingInvitations"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "listIncomingInvitations", args);
  },
});

export const listInvitations = query({
  args: getPublicPluginFunctionArgs(pluginGateway.listInvitations, "listInvitations"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "listInvitations", args);
  },
});

export const listMembers = query({
  args: getPublicPluginFunctionArgs(pluginGateway.listMembers, "listMembers"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "listMembers", args);
  },
});

export const listOrganizations = query({
  args: getPublicPluginFunctionArgs(pluginGateway.listOrganizations, "listOrganizations"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "listOrganizations", args);
  },
});

export const listRoles = query({
  args: getPublicPluginFunctionArgs(pluginGateway.listRoles, "listRoles"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "listRoles", args);
  },
});

export const markDomainVerified = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.markDomainVerified, "markDomainVerified"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "markDomainVerified", args);
  },
});

export const removeDomain = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.removeDomain, "removeDomain"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "removeDomain", args);
  },
});

export const removeMember = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.removeMember, "removeMember"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "removeMember", args);
  },
});

export const requirePermission = query({
  args: getPublicPluginFunctionArgs(pluginGateway.requirePermission, "requirePermission"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "requirePermission", args);
  },
});

export const requireRole = query({
  args: getPublicPluginFunctionArgs(pluginGateway.requireRole, "requireRole"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "requireRole", args);
  },
});

export const resolveOrganizationByHost = query({
  args: getPublicPluginFunctionArgs(pluginGateway.resolveOrganizationByHost, "resolveOrganizationByHost"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "resolveOrganizationByHost", args);
  },
});

export const setMemberRole = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.setMemberRole, "setMemberRole"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "setMemberRole", args);
  },
});

export const transferOwnership = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.transferOwnership, "transferOwnership"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "transferOwnership", args);
  },
});

export const updateOrganization = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.updateOrganization, "updateOrganization"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "updateOrganization", args);
  },
});

export const updateRole = mutation({
  args: getPublicPluginFunctionArgs(pluginGateway.updateRole, "updateRole"),
  handler: async (ctx, args) => {
    return runPluginRuntimeFunction(ctx, "updateRole", args);
  },
});
