// @generated by convex-zen generate. DO NOT EDIT.
import { v } from "convex/values";
import { mutation, query } from "../../_generated/server";
import { auth } from "../generated";

async function requireActorUserId(ctx: { auth: { getUserIdentity: () => Promise<{ subject?: string } | null> } }): Promise<string> {
  const identity = await ctx.auth.getUserIdentity();
  const actorUserId = identity?.subject;
  if (!actorUserId) {
    throw new Error("Unauthorized: missing identity subject");
  }
  return actorUserId;
}

export const isAdmin = query({
  args: {
    actorUserId: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const identity = await ctx.auth.getUserIdentity();
    const actorUserId = identity?.subject;
    if (!actorUserId) {
      return false;
    }
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.admin.isAdmin(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const listUsers = query({
  args: {
    actorUserId: v.optional(v.string()),
    limit: v.optional(v.number()),
    cursor: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.admin.listUsers(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const banUser = mutation({
  args: {
    actorUserId: v.optional(v.string()),
    userId: v.string(),
    reason: v.optional(v.string()),
    expiresAt: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.admin.banUser(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const unbanUser = mutation({
  args: {
    actorUserId: v.optional(v.string()),
    userId: v.string(),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.admin.unbanUser(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const setRole = mutation({
  args: {
    actorUserId: v.optional(v.string()),
    userId: v.string(),
    role: v.string(),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.admin.setRole(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});

export const deleteUser = mutation({
  args: {
    actorUserId: v.optional(v.string()),
    userId: v.string(),
  },
  handler: async (ctx, args) => {
    const actorUserId = await requireActorUserId(ctx);
    const { actorUserId: _ignoredActorUserId, ...inputArgs } = args as Record<string, unknown>;
    return auth.plugins.admin.deleteUser(ctx, {
      ...inputArgs,
      actorUserId,
    } as any);
  },
});
