// @generated by convex-zen generate. DO NOT EDIT.
export const authPluginMeta = {
  "admin": {
    "banUser": "mutation",
    "deleteUser": "mutation",
    "isAdmin": "query",
    "listUsers": "query",
    "setRole": "mutation",
    "unbanUser": "mutation"
  }
} as const;

export type AuthPluginMeta = typeof authPluginMeta;
